services:
  build:
    build: .
    volumes:
      - ./dist:/app/dist
    command: sh -lc "rm -rf dist/* && pnpm exec tsc && pnpm exec gulp build:icons"

  publish:
    build: .
    env_file:
      - .env
    command: sh -c "echo '//registry.npmjs.org/:_authToken=$${NPM_TOKEN}' > ~/.npmrc && npm publish --access public"
