import { INodeProperties } from 'n8n-workflow';

export const CentumOperations: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'Article', value: 'articles' },
			{ name: 'Customer', value: 'customers' },
			{ name: 'Extra', value: 'extras' },
			{ name: 'Geography', value: 'geography' },
			{ name: 'Logistic', value: 'logistics' },
			{ name: 'Payment', value: 'payments' },
			{ name: 'Purchase', value: 'purchases' },
			{ name: 'Sale', value: 'sales' },
			{ name: 'Stock', value: 'stock' },
			{ name: 'Supplier', value: 'suppliers' },
		],
		default: 'sales',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['articles'] } },
		options: [
			{
				name: 'Article - By ID',
				value: 'getProductByCode',
				action: 'Get article by ID',
				description: 'Return a specific article based on its unique ID',
			},
			{
				name: 'Article - Search',
				value: 'searchProducts',
				action: 'Search articles by name',
				description: 'Search for an article by name and return every match',
			},
			{
				name: 'Articles - Filtered',
				value: 'listAvailableProducts',
				action: 'List filtered articles',
				description: 'Return a list of sellable articles using the selected filters',
			},
			{
				name: 'Articles - Image',
				value: 'downloadProductImages',
				action: 'Get article image',
				description: 'Return the binary image for an article',
			},
			{
				name: 'Articles - List',
				value: 'listAllProducts',
				action: 'List article details',
				description: 'Return a list of articles and their general data',
			},
			{
				name: 'Articles - Price by List',
				value: 'getProductPrice',
				action: 'Get article price by list',
				description: 'Return the article price for the selected price list',
			},
			{
				name: 'Articles - Stock by Branch and Article ID',
				value: 'getProductInBranch',
				action: 'Get branch stock by article',
				description: 'Return stock for a specific article in a physical branch',
			},
			{
				name: 'Articles - Stock by Physical Branch',
				value: 'listProductsByBranch',
				action: 'List stock by physical branch',
				description: 'Return article stock for a specific physical branch',
			},
			{
				name: 'Brands - Get',
				value: 'listBrands',
				action: 'List brands',
				description: 'Get the complete list of article brands',
			},
			{
				name: 'Categories - Get',
				value: 'listCategories',
				action: 'List categories',
				description: 'Get the complete list of article categories',
			},
			{
				name: 'Discounts - Get',
				value: 'listDiscounts',
				action: 'List discounts',
				description: 'Get the complete list of available discounts',
			},
			{
				name: 'Groups - Get',
				value: 'listGroups',
				action: 'List groups',
				description: 'Get the complete list of article groups',
			},
			{
				name: 'Product Prices - List',
				value: 'listPrices',
				action: 'List product prices',
				description: 'Get a list of suggested product prices',
			},
			{
				name: 'Subgroups - List',
				value: 'listSubgroups',
				action: 'List subgroups',
				description: 'Get the complete list of article subgroups or filter them by ID',
			},
		],
		default: 'searchProducts',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['customers'] } },
		options: [
			{
				name: 'Customer - Create',
				value: 'createCustomer',
				action: 'Create customer',
				description: 'Create a new customer',
			},
			{
				name: 'Customer - Get Balance',
				value: 'getCustomerBalance',
				action: 'Get customer balance',
				description: 'Get the balance for the selected customer',
			},
			{
				name: 'Customer - Get Balance Breakdown',
				value: 'getCustomerBalanceDetails',
				action: 'Get customer balance breakdown',
				description: 'Get the account balance breakdown for the selected customer',
			},
			{
				name: 'Customer - Get Commercial Promotions',
				value: 'listCustomerCommercialPromotions',
				action: 'Get customer commercial promotions',
				description: 'Get the commercial promotions applied to a customer from the selected date',
			},
			{
				name: 'Customer - Get Payment Invoices',
				value: 'listPaymentInvoices',
				action: 'Get payment invoices',
				description: 'Get all payment invoices for the selected customer',
			},
			{
				name: 'Customer - Get Sales Invoices',
				value: 'listSalesInvoices',
				action: 'Get sales invoices',
				description: 'Get all sales invoices for the selected customer',
			},
			{
				name: 'Customer - Get Sales Invoices by ID',
				value: 'listSalesInvoicesById',
				action: 'Get sales invoices by ID',
				description: 'Get all sales invoices for the selected customer by ID',
			},
			{
				name: 'Customer - List',
				value: 'listCustomers',
				action: 'List customers',
				description: 'Return a list of all registered customers',
			},
			{
				name: 'Customer - Search',
				value: 'searchCustomers',
				action: 'Search customers',
				description: 'Return a list of customers that match the selected filters',
			},
			{
				name: 'Customer - Search by CUIT',
				value: 'searchCustomerByCuit',
				action: 'Search customers by CUIT',
				description: 'Return a list of customers based on the provided CUIT',
			},
			{
				name: 'Customer - Update',
				value: 'updateCustomer',
				action: 'Update customer',
				description: 'Update a customer and return the resource information and URL',
			},
			{
				name: 'Customer Frequencies - List',
				value: 'listCustomerFrequencies',
				action: 'List customer frequencies',
				description: 'Get a list of customer frequency options',
			},
			{
				name: 'Taxpayer Customer - Create',
				value: 'createTaxpayerCustomer',
				action: 'Create taxpayer customer',
				description: 'Create a new taxpayer customer',
			},
			{
				name: 'Taxpayer Customer - Search',
				value: 'searchTaxpayerCustomer',
				action: 'Search taxpayer customer',
				description: 'Return taxpayer data by CUIT or business name',
			},
		],
		default: 'updateCustomer',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['sales'] } },
		options: [
			{
				name: 'Commercial Promotions - List',
				value: 'listPromotions',
				action: 'List commercial promotions',
				description: 'Get the available commercial promotions',
			},
			{
				name: 'Sales - Create',
				value: 'createSale',
				action: 'Create sale',
				description: 'Create a sale from the completed parameters',
			},
			{
				name: 'Sales Order - Create',
				value: 'createSalesOrder',
				action: 'Create sales order',
				description: 'Create a sales order using the provided articles',
			},
			{
				name: 'Sales Order - Get',
				value: 'getSalesOrderDetails',
				action: 'Get sales order',
				description: 'Get a sales order by its unique identifier',
			},
			{
				name: 'Sales Order Statuses - List',
				value: 'listSalesOrderStatuses',
				action: 'List sales order statuses',
				description: 'Get all available sales order statuses',
			},
			{
				name: 'Sales Orders - List',
				value: 'listSalesOrders',
				action: 'List sales orders',
				description: 'Get all sales orders using the selected filters',
			},
			{
				name: 'Sales Orders - Summary',
				value: 'listFilteredSalesOrders',
				action: 'List summarized sales orders',
				description: 'Get sales orders with a lighter response body',
			},
			{
				name: 'Sales Ranking - Get',
				value: 'getSalesRanking',
				action: 'Get sales ranking',
				description: 'Get a ranking of customers, articles, sellers, or branches',
			},
			{
				name: 'Sales Voucher - List',
				value: 'listSalesVouchers',
				action: 'List sales vouchers',
				description: 'Get a list of sales vouchers using the selected filters',
			},
		],
		default: 'listSalesVouchers',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['payments'] } },
		options: [
			{
				name: 'Payment - Create',
				value: 'registerPayment',
				action: 'Create payment',
				description: 'Create a payment voucher',
			},
			{
				name: 'Payments - List',
				value: 'listPayments',
				action: 'List payments',
				description: 'Get a list of payments using the selected filters',
			},
		],
		default: 'registerPayment',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['purchases'] } },
		options: [
			{
				name: 'Purchase Delivery Note - Create',
				value: 'createPurchaseDeliveryNote',
				action: 'Create purchase delivery note',
				description: 'Create a purchase delivery note from the provided parameters',
			},
			{
				name: 'Purchase Order - Create',
				value: 'createPurchaseOrder',
				action: 'Create purchase order',
				description: 'Create a purchase order using the selected parameters',
			},
			{
				name: 'Purchase Order - Get',
				value: 'getPurchaseOrderDetails',
				action: 'Get purchase order',
				description: 'Get a single purchase order by ID',
			},
			{
				name: 'Purchase Orders - List',
				value: 'listPurchaseOrders',
				action: 'List purchase orders',
				description: 'Get all purchase orders using the selected filters',
			},
			{
				name: 'Purchase Voucher - List',
				value: 'listPurchaseVouchers',
				action: 'List purchase vouchers',
				description: 'Get a list of purchase vouchers using the selected filters',
			},
			{
				name: 'Purchases - Create',
				value: 'createPurchase',
				action: 'Create purchase',
				description: 'Create a purchase using the selected parameters',
			},
			{
				name: 'Purchases - List',
				value: 'listPurchases',
				action: 'List purchases',
				description: 'Get a list of purchases using the selected filters',
			},
		],
		default: 'createPurchase',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['suppliers'] } },
		options: [
			{
				name: 'Supplier - Search',
				value: 'searchSupplier',
				action: 'Search supplier',
				description: 'Return supplier information based on its ID',
			},
			{
				name: 'Supplier - Create',
				value: 'createSupplier',
				action: 'Create supplier',
				description: 'Create a supplier using the provided data',
			},
			{
				name: 'Suppliers - List',
				value: 'listSuppliers',
				action: 'List suppliers',
				description: 'Get a complete list of suppliers',
			},
		],
		default: 'searchSupplier',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['logistics'] } },
		options: [
			{
				name: 'Delivery Time Slots - List',
				value: 'listDeliveryTimeSlots',
				action: 'List delivery time slots',
				description: 'Get the full list of available delivery time slots',
			},
			{
				name: 'Drivers - List',
				value: 'listDrivers',
				action: 'List drivers',
				description: 'Get the complete list of available drivers',
			},
			{
				name: 'Physical Branches - List',
				value: 'listPhysicalBranches',
				action: 'List physical branches',
				description: 'Get the available physical branches',
			},
			{
				name: 'Sales Delivery Note - Create',
				value: 'createSalesDeliveryNote',
				action: 'Create sales delivery note',
				description: 'Create a sales delivery note from the provided parameters',
			},
			{
				name: 'Sellers - List',
				value: 'listSellers',
				action: 'List sellers',
				description: 'Get a list of all available sellers',
			},
		],
		default: 'listDrivers',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['stock'] } },
		options: [
			{
				name: 'Article Locations - List',
				value: 'listArticleLocations',
				action: 'List article locations',
				description: 'Get the complete list of article locations',
			},
			{
				name: 'Articles - Stock',
				value: 'getStock',
				action: 'Get article stock',
				description: 'Return article stock using the selected filters',
			},
			{
				name: 'Transfer Order - Create',
				value: 'createStockMovement',
				action: 'Create stock movement',
				description: 'Create a stock movement adjustment',
			},
		],
		default: 'getStock',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['geography'] } },
		options: [
			{
				name: 'Countries - List',
				value: 'listCountries',
				action: 'List countries',
				description: 'Get the list of available countries',
			},
			{
				name: 'Municipalities - List',
				value: 'listMunicipalities',
				action: 'List municipalities',
				description: 'Get a list of municipalities, usually filtered by province',
			},
			{
				name: 'Provinces - List',
				value: 'listProvinces',
				action: 'List provinces',
				description: 'Get a list of provinces, usually filtered by country',
			},
		],
		default: 'listMunicipalities',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['extras'] } },
		options: [
			{
				name: 'Access Token - Generate',
				value: 'generateSecurityToken',
				action: 'Generate access token',
				description: 'Generate a token for external tools such as Postman',
			},
			{
				name: 'Binary to Image',
				value: 'syncImages',
				action: 'Process binary images',
				description: 'Process binary image data for WooCommerce usage',
			},
			{
				name: 'Concepts - List',
				value: 'listConcepts',
				action: 'List concepts',
				description: 'Get a list of concepts',
			},
			{
				name: 'Mobile Operator - Verify',
				value: 'verifyOperatorCredentials',
				action: 'Verify mobile operator',
				description: 'Get the data for a mobile operator using the configured credentials',
			},
			{
				name: 'Mobile Operators - List',
				value: 'listMobileOperators',
				action: 'List mobile operators',
				description: 'Get the list of all mobile operators',
			},
			{
				name: 'Special Tax Regimes - By ID',
				value: 'getSpecialTaxRegimeDetails',
				action: 'Get special tax regime by ID',
				description: 'Get a special tax regime by ID',
			},
			{
				name: 'Special Tax Regimes - List',
				value: 'listSpecialTaxRegimes',
				action: 'List special tax regimes',
				description: 'Get the complete list of special tax regimes',
			},
			{
				name: 'Voucher Types - List',
				value: 'listVoucherTypes',
				action: 'List voucher types',
				description: 'Get a list of all voucher types',
			},
			{
				name: 'WooCommerce Products - Generate (Product JSON)',
				value: 'convertProductsForWooCommerce',
				action: 'Convert woo commerce products',
				description: 'Generate structured WooCommerce product JSON from Centum articles',
			},
		],
		default: 'generateSecurityToken',
	},
];
