import { INodeProperties } from "n8n-workflow";

export const CentumOperations: INodeProperties[] = [
	{
		displayName: "Resource",
		name: "resource",
		type: "options",
		noDataExpression: true,
		options: [
			{
				name: "Artículos",
				value: "articulos",
			},
			{
				name: "Clientes",
				value: "clientes",
			},
			{
				name: "Ventas",
				value: "ventas",
			},
			{
				name: "Cobros",
				value: "cobros",
			},
			{
				name: "Compras",
				value: "compras",
			},
			{
				name: "Proveedores",
				value: "proveedores",
			},
			{
				name: "Logística",
				value: "logistica",
			},
			{
				name: "Stock",
				value: "stock",
			},
			{
				name: "Geografía",
				value: "geografia",
			},
			{
				name: "Extras",
				value: "extras",
			},
		],
		default: "ventas",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["articulos"],
			},
		},
		options: [
			{
				name: "Artículo - Buscar",
				value: "buscarProductos",
				action: "Busca artículos por nombre",
				description: "Busca un artículo por nombre y retorna todas las ocurrencias",
			},
			{
				name: "Artículo - Por ID",
				value: "buscarProductoPorCodigo",
				action: "Busca artículo por ID",
				description: "Retorna un artículo específico basado en su ID único",
			},
			{
				name: "Artículos - Filtrado",
				value: "listarProductosDisponibles",
				action: "Lista artículos con filtros",
				description: "Retorna un listado de artículos para vender en base a ciertos filtros",
			},
			{
				name: "Artículos - Imagen",
				value: "descargarImagenesProductos",
				action: "Obtiene imagen de artículo",
				description: "Retorna la imagen binaria de un artículo",
			},
			{
				name: "Artículos - Listado",
				value: "listarTodosLosProductos",
				action: "Lista datos generales de artículos",
				description: "Retorna un listado de los artículos y sus datos generales",
			},
			{
				name: "Artículos - Precio Por Lista",
				value: "consultarPrecioProducto",
				action: "Obtiene precio por lista",
				description: "Devuelve el valor de un artículo según la lista indicada",
			},
			{
				name: "Artículos - Stock Sucursal Física",
				value: "listarProductosPorSucursal",
				action: "Lista stock por sucursal física",
				description: "Retorna el stock de artículos en una sucursal física específica",
			},
			{
				name: "Artículos - Stock Sucursal Física Por ID Artículo",
				value: "buscarProductoEnSucursal",
				action: "Obtiene stock por artículo en sucursal",
				description: "Retorna el stock de un artículo específico en una sucursal física",
			},
			{
				name: "Bonificaciones - Obtener",
				value: "listarBonificaciones",
				action: "Lista bonificaciones",
				description: "Obtiene el listado completo de bonificaciones disponibles",
			},
			{
				name: "Categorías - Obtener",
				value: "listarCategorias",
				action: "Lista categorías",
				description: "Obtiene el listado completo de todas las categorías de los artículos",
			},
			{
				name: "Marcas - Obtener",
				value: "listarMarcas",
				action: "Lista marcas",
				description: "Obtiene el listado completo de las marcas de los artículos",
			},
			{
				name: "Precios De Productos - Lista",
				value: "listarPrecios",
				action: "Lista precios de productos",
				description: "Obtiene una lista con los precios sugeridos",
			},
			{
				name: "Rubros - Obtener",
				value: "listarRubros",
				action: "Lista rubros",
				description: "Obtiene el listado completo de los rubros de los artículos",
			},
			{
				name: "Sub Rubros - Listar",
				value: "listarSubRubros",
				action: "Lista sub rubros",
				description: "Obtiene el listado completo de los sub rubros o los filtra por ID",
			},
		],
		default: "buscarProductos",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["clientes"],
			},
		},
		options: [
			{
				name: "Cliente - Actualizar",
				value: "actualizarCliente",
				action: "Actualiza cliente",
				description: "Actualiza un cliente y retorna su información con la URL para acceder al recurso",
			},
			{
				name: "Cliente - Búsqueda",
				value: "buscarClientes",
				action: "Busca clientes",
				description: "Retorna un listado de clientes en base a ciertos filtros",
			},
			{
				name: "Cliente - Búsqueda Por CUIT",
				value: "buscarClientePorCuit",
				action: "Busca clientes por CUIT",
				description: "Retorna un listado de clientes basado en el CUIT proporcionado",
			},
			{
				name: "Cliente - Lista",
				value: "listarClientes",
				action: "Lista clientes",
				description: "Retorna una lista con todos los clientes registrados",
			},
			{
				name: "Cliente - Nuevo",
				value: "crearCliente",
				action: "Crea cliente",
				description: "Da de alta un cliente nuevo",
			},
			{
				name: "Cliente - Obtener Composición Del Saldo",
				value: "verDetalleSaldoCliente",
				action: "Obtiene composición del saldo",
				description: "Obtiene la composición del saldo de la cuenta corriente del cliente especificado",
			},
			{
				name: "Cliente - Obtener Facturas De Cobro",
				value: "listarFacturasCobros",
				action: "Obtiene facturas de cobro",
				description: "Obtiene la totalidad de las facturas de los cobros del cliente especificado",
			},
			{
				name: "Cliente - Obtener Facturas De Venta",
				value: "listarFacturasVenta",
				action: "Obtiene facturas de venta",
				description: "Obtiene la totalidad de las facturas de los pedidos de venta del cliente especificado",
			},
			{
				name: "Cliente - Obtener Facturas De Venta Por ID",
				value: "listarFacturasVentasPorID",
				action: "Obtiene facturas de venta por ID",
				description: "Obtiene la totalidad de las facturas de ventas del cliente especificado",
			},
			{
				name: "Cliente - Obtener Promoción Comercial",
				value: "listarPromocionesComercialesCliente",
				action: "Obtiene promociones comerciales del cliente",
				description: "Obtiene las promociones comerciales aplicadas a un cliente desde una fecha seleccionada",
			},
			{
				name: "Cliente - Obtener Saldo",
				value: "consultarSaldoCliente",
				action: "Obtiene saldo del cliente",
				description: "Obtiene el saldo del cliente especificado",
			},
			{
				name: "Cliente Contribuyente - Búsqueda",
				value: "buscarContribuyente",
				action: "Busca cliente contribuyente",
				description: "Retorna los datos del contribuyente por CUIT o razón social",
			},
			{
				name: "Cliente Contribuyente - Nuevo",
				value: "crearContribuyente",
				action: "Crea cliente contribuyente",
				description: "Da de alta un cliente contribuyente nuevo",
			},
			{
				name: "Frecuencias Clientes - Listar",
				value: "frecuenciasCliente",
				action: "Lista frecuencias de clientes",
				description: "Obtiene un listado con las frecuencias de los clientes",
			},
		],
		default: "actualizarCliente",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["ventas"],
			},
		},
		options: [
			{
				name: "Comprobante De Venta - Obtener Listado",
				value: "listarComprobantesVenta",
				action: "Lista comprobantes de venta",
				description: "Obtiene un listado de los comprobantes de venta en base a ciertos parámetros",
			},
			{
				name: "Estadística Ranking - Venta",
				value: "estadisticaVentaRanking",
				action: "Obtiene ranking de ventas",
				description: "Obtiene un listado de clientes, artículos, vendedores o sucursales según un ranking de venta",
			},
			{
				name: "Pedido De Venta - Actividad",
				value: "verDetallePedidoVenta",
				action: "Obtiene pedido de venta",
				description: "Trae un pedido de venta por un identificador único",
			},
			{
				name: "Pedido De Venta - Nuevo",
				value: "crearPedidoVenta",
				action: "Crea pedido de venta",
				description: "Realiza pedidos de venta de los artículos",
			},
			{
				name: "Pedidos De Venta - Estado",
				value: "listarEstadosPedidosVenta",
				action: "Lista estados de pedidos de venta",
				description: "Obtiene todos los estados disponibles de los pedidos de venta",
			},
			{
				name: "Pedidos De Venta - Listar",
				value: "listarPedidosVenta",
				action: "Lista pedidos de venta",
				description: "Obtiene todos los pedidos de venta en base a ciertos parámetros",
			},
			{
				name: "Pedidos De Venta - Resumido",
				value: "listarPedidosVentaFiltrados",
				action: "Lista pedidos de venta resumidos",
				description: "Obtiene todos los pedidos de venta con un cuerpo de respuesta más ligero",
			},
			{
				name: "Promociones Comerciales - Lista",
				value: "listarPromociones",
				action: "Lista promociones comerciales",
				description: "Obtiene las promociones comerciales disponibles",
			},
			{
				name: "Ventas - Generar",
				value: "crearVenta",
				action: "Genera venta",
				description: "Genera una venta en base a parámetros completados",
			},
		],
		default: "listarComprobantesVenta",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["cobros"],
			},
		},
		options: [
			{
				name: "Cobro - Nuevo",
				value: "registrarCobro",
				action: "Registra cobro",
				description: "Da de alta el comprobante de cobro",
			},
			{
				name: "Cobro - Obtener Listado",
				value: "listarCobros",
				action: "Lista cobros",
				description: "Obtiene un listado de cobros en base a ciertos parámetros",
			},
		],
		default: "registrarCobro",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["compras"],
			},
		},
		options: [
			{
				name: "Compras - Generar Compra",
				value: "crearCompra",
				action: "Genera compra",
				description: "Genera una compra desde los parámetros especificados",
			},
			{
				name: "Compras - Obtener Listado",
				value: "listarCompras",
				action: "Lista compras",
				description: "Obtiene un listado de las compras en base a ciertos parámetros",
			},
			{
				name: "Comprobante De Compra - Obtener Listado",
				value: "listarComprobantesCompra",
				action: "Lista comprobantes de compra",
				description: "Obtiene un listado de los comprobantes de compra en base a ciertos parámetros",
			},
			{
				name: "Orden De Compra - Generar",
				value: "crearOrdenCompra",
				action: "Genera orden de compra",
				description: "Genera una orden de compra en base a ciertos parámetros",
			},
			{
				name: "Orden De Compra - Obtener",
				value: "verDetalleOrdenCompra",
				action: "Obtiene orden de compra",
				description: "Obtiene una única orden de compra en base al ID",
			},
			{
				name: "Órdenes De Compra - Obtener",
				value: "listarOrdenesCompra",
				action: "Lista órdenes de compra",
				description: "Obtiene todas las órdenes de compra en base a ciertos filtros",
			},
			{
				name: "Remito De Compra - Crear",
				value: "crearRemitoCompra",
				action: "Crea remito de compra",
				description: "Crea un remito de compra en base a los parámetros enviados",
			},
		],
		default: "crearCompra",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["proveedores"],
			},
		},
		options: [
			{
				name: "Proveedor - Buscar",
				value: "buscarProveedor",
				action: "Busca proveedor",
				description: "Retorna la información del proveedor en base al ID",
			},
			{
				name: "Proveedor - Crear",
				value: "crearProveedor",
				action: "Crea proveedor",
				description: "Crea un proveedor en base a los datos enviados",
			},
			{
				name: "Proveedores - Listar",
				value: "listarProveedores",
				action: "Lista proveedores",
				description: "Obtiene una lista completa de los proveedores",
			},
		],
		default: "buscarProveedor",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["logistica"],
			},
		},
		options: [
			{
				name: "Choferes - Obtener Listado",
				value: "listarChoferes",
				action: "Lista choferes",
				description: "Obtiene un listado completo de los choferes disponibles",
			},
			{
				name: "Remito De Venta - Crear",
				value: "crearRemitoVenta",
				action: "Crea remito de venta",
				description: "Crea un remito de venta en base a los parámetros enviados",
			},
			{
				name: "Sucursales Físicas - Lista",
				value: "listarSucursales",
				action: "Lista sucursales físicas",
				description: "Obtiene un listado de las sucursales físicas disponibles",
			},
			{
				name: "Turno De Entrega - Obtener",
				value: "listarTurnosEntrega",
				action: "Lista turnos de entrega",
				description: "Obtiene el listado total disponible de turnos de entrega",
			},
			{
				name: "Vendedores - Obtener",
				value: "listarVendedores",
				action: "Lista vendedores",
				description: "Obtiene una lista de todos los vendedores disponibles",
			},
		],
		default: "listarChoferes",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["stock"],
			},
		},
		options: [
			{
				name: "Artículos - Existencia",
				value: "consultarStock",
				action: "Consulta existencias de artículos",
				description: "Retorna un listado de las existencias de los artículos en base a ciertos filtros",
			},
			{
				name: "Orden De Traspaso - Generar",
				value: "crearMovimientoStock",
				action: "Genera movimiento de stock",
				description: "Crea un ajuste de movimiento de stock",
			},
			{
				name: "Ubicaciones De Artículos - Listar",
				value: "listarUbicacionArticulos",
				action: "Lista ubicaciones de artículos",
				description: "Obtiene un listado total de las ubicaciones de los artículos",
			},
		],
		default: "consultarStock",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["geografia"],
			},
		},
		options: [
			{
				name: "Municipios - Lista",
				value: "listarMunicipios",
				action: "Lista municipios",
				description: "Obtiene un listado de los municipios, normalmente filtrado por provincia",
			},
			{
				name: "País - Obtener Listado",
				value: "listarPaises",
				action: "Lista países",
				description: "Obtiene el listado de países disponibles",
			},
			{
				name: "Provincias - Lista",
				value: "listarProvincias",
				action: "Lista provincias",
				description: "Obtiene un listado de provincias, normalmente filtrado por país",
			},
		],
		default: "listarMunicipios",
	},
	{
		displayName: "Operación",
		name: "operation",
		type: "options",
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ["extras"],
			},
		},
		options: [
			{
				name: "_Token De Acceso - Generación",
				value: "generarTokenSeguridad",
				action: "Genera un nuevo token",
				description: "Genera un nuevo token para utilizarlo con una herramienta externa como Postman",
			},
			{
				name: "Conceptos - Obtener Listado",
				value: "listarConceptos",
				action: "Lista conceptos",
				description: "Obtiene un listado de conceptos",
			},
			{
				name: "Obtener Operador Móvil",
				value: "listarOperadoresMoviles",
				action: "Lista operadores móviles",
				description: "Obtiene el listado de todos los operadores móviles",
			},
			{
				name: "Proceso Binario a Imagen",
				value: "sincronizarImagenes",
				action: "Procesa imágenes binarias",
				description: "Procesa datos binarios de imágenes para su uso en WooCommerce",
			},
			{
				name: "Productos WooCommerce - Generar (JSON Producto)",
				value: "convertirProductosParaWooCommerce",
				action: "Convierte productos para WooCommerce",
				description: "Genera un JSON estructurado para productos WooCommerce a partir de artículos Centum",
			},
			{
				name: "Regímenes Especiales - ID",
				value: "verDetalleRegimenEspecial",
				action: "Obtiene régimen especial por ID",
				description: "Trae un régimen especial por ID",
			},
			{
				name: "Regímenes Especiales - Lista",
				value: "listarRegimenesEspeciales",
				action: "Lista regímenes especiales",
				description: "Trae un listado completo de los regímenes especiales",
			},
			{
				name: "Tipo De Comprobante - Lista",
				value: "listarTiposComprobante",
				action: "Lista tipos de comprobante",
				description: "Obtiene un listado de todos los tipos de comprobantes",
			},
			{
				name: "Verificar Operador Móvil",
				value: "verificarCredencialesOperador",
				action: "Verifica operador móvil",
				description: "Obtiene todos los datos de un operador móvil en base a las credenciales",
			},
		],
		default: "generarTokenSeguridad",
	},
];
const getArticulo: INodeProperties[] = [
	{
		displayName: "Activo",
		name: "active",
		type: "boolean",
		default: false,
		displayOptions: {
			show: { operation: ["crearProveedor", "listarProveedores"] },
		},
	},
	{
		displayName: "Articulos",
		name: "articulo",
		required: true,
		type: "json",
		default: {},
		displayOptions: {
			show: { operation: ["registrarCobro", "crearPedidoVenta", "crearOrdenCompra", "crearRemitoCompra"] },
		},
	},
	{
		displayName: "Artículos",
		name: "articlesCollection",
		type: "string",
		placeholder: '[{ "ID": 1234, "Cantidad": 10 }, {"ID": 4567, "Cantidad": 5}]',
		default: "",
		description: "Lista de artículos en formato JSON",
		displayOptions: {
			show: { operation: ["crearCompra", "crearVenta", "crearRemitoVenta"] },
		},
	},
	{
		displayName: "Cantidad De Cuotas Efectivo",
		name: "cantidadCuotasValorEfectivo",
		type: "number",
		default: 0,
		displayOptions: { show: { esContado: [true] } },
	},
	// {
	// 	displayName: 'Cantidad Por Página',
	// 	name: 'cantidadPorPagina',
	// 	type: 'number',
	// 	default: 50,
	// 	description: 'Cantidad de artículos por página',
	// 	displayOptions: { show: { operation: ['articulo'] } },
	// },
	{
		displayName: "Categoría De Impuestos A Las Ganancias",
		name: "categoriaImpuestosGanancias",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "Clase De Proveedor",
		name: "claseProveedor",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "Cliente",
		name: "cliente",
		required: true,
		type: "json",
		default: {},
		displayOptions: {
			show: { operation: ["registrarCobro"] },
		},
	},
	{
		displayName: "Fecha De Entrega Desde",
		name: "fromDeliveryDate",
		type: "dateTime",
		default: {},
		displayOptions: {
			show: { operation: ["listarOrdenesCompra"] },
		},
	},
	{
		displayName: "Fecha De Entrega Hasta",
		name: "sinceDeliveryDate",
		type: "dateTime",
		default: {},
		displayOptions: {
			show: { operation: ["listarOrdenesCompra"] },
		},
	},
	{
		displayName: "Cliente ID",
		name: "clienteId",
		type: "number",
		required: true,
		typeOptions: { maxValue: 9999999, minValue: 0, numberStepSize: 1 },
		default: 0,
		description: "Client ID used to search the articles",
		displayOptions: {
			show: {
				operation: [
					"crearCompra",
					"listarProductosDisponibles",
					"consultarSaldoCliente",
					"verDetalleSaldoCliente",
					"listarFacturasVenta",
					"listarFacturasCobros",
					"listarPromocionesComercialesCliente",
					"listarPedidosVenta",
					"listarOrdenesCompra",
					"listarCobros",
					"listarCompras",
					"crearVenta",
					"listarPedidosVentaFiltrados",
					"consultarPrecioProducto",
					"crearRemitoVenta",
					"crearRemitoCompra",
				],
			},
		},
	},
	{
		displayName: "Codigo Artículo",
		name: "codigoArticulo",
		type: "string",
		default: "",
		placeholder: '[{ "ID": 1234, "Cantidad": 10 }, {"ID": 4567, "Cantidad": 5}]',
		description: 'Codigo del articulo a buscar. (Separa con "," si necesitas mas de uno.',
		displayOptions: {
			show: {
				operation: ["buscarProductoPorCodigo", "buscarProductos"],
			},
		},
	},
	{
		displayName: "Codigo Cliente",
		name: "codigoCliente",
		type: "string",
		default: "",
		typeOptions: { minValue: 1 },
		placeholder: "Ej. 1507",
		description: "Codigo del cliente a buscar",
		displayOptions: {
			show: {
				operation: ["buscarClientes", "crearPedidoVenta"],
			},
		},
	},
	{
		displayName: "Código Del Comprobante",
		name: "codigoComprobante",
		type: "string",
		default: "",
		placeholder: "Codigo de la compra (FCC)",
		description: "Codigo del comprobante de la compra",
		displayOptions: { show: { operation: ["crearCompra"] } },
	},
	{
		displayName: "Condicion De Venta",
		name: "idCondicionVenta",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearVenta", "crearCliente"] } },
	},
	{
		displayName: "Condición De Pago",
		name: "condicionDePago",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "ID Condición IVA",
		name: "condicionIVA",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearProveedor", "crearCliente"] } },
	},
	{
		displayName: "Cotizacion",
		name: "cotizacionValorEfectivo",
		type: "number",
		default: 0,
		displayOptions: { show: { esContado: [true] } },
	},
	// {
	// 	displayName: 'Cuerpo Del Pedido',
	// 	name: 'cuerpoHTTP',
	// 	type: 'json',
	// 	required: true,
	// 	default: "",
	// 	displayOptions: {
	// 		show: {
	// 			operation: ['crearCliente', 'actualizarCliente', 'crearContribuyente'],
	// 		},
	// 	},
	// 	description: 'Información en formato JSON para crear o actualizar un cliente',
	// },
	{
		displayName: "CUIT",
		name: "cuit",
		type: "string",
		default: "",
		placeholder: "Ingresá el CUIT...",
		displayOptions: {
			show: {
				operation: ["crearProveedor", "crearCliente", "buscarContribuyente", "crearContribuyente", "buscarClientePorCuit", "buscarClientes", "listarProveedores"],
			},
		},
	},
	{
		displayName: "Datos Imagen",
		name: "dataImg",
		type: "json",
		required: true,
		default: "",
		displayOptions: { show: { operation: ["sincronizarImagenes"] } },
	},
	{
		displayName: "Dia De La Semana",
		name: "diaSemana",
		type: "number",
		default: 0,
		description: "Numero de la semana por el cual filtrar promociones aplicadas (0 es Lunes)",
		displayOptions: { show: { operation: ["listarPromocionesComercialesCliente"] } },
	},
	// {
	// 	displayName: 'DNI',
	// 	name: 'dni',
	// 	type: 'string',
	// 	default: '',
	// 	displayOptions: { show: { operation: ['crearCliente'] } },
	// },
	// {
	// 	displayName: 'Documento',
	// 	name: 'documentDate',
	// 	type: 'dateTime',
	// 	required: true,
	// 	default: undefined,
	// 	description: 'Parametro fecha del body para las solicitudes',
	// 	displayOptions: {
	// 		show: { operation: ['articulo', 'promocionesCliente', 'generarCompras'] },
	// 	},
	// },
	{
		displayName: "Endpoint",
		name: "endpoint",
		type: "string",
		default: "/Clientes",
		required: true,
		placeholder: "/Clientes, /Articulos/Venta, etc.",
		description: "Ruta del endpoint a utilizar",
		displayOptions: { show: { operation: [] } },
	},
	{
		displayName: "Es Contado",
		name: "esContado",
		type: "boolean",
		default: false,
		displayOptions: { show: { operation: ["crearVenta"] } },
	},
	{
		displayName: "Fecha Desde",
		name: "startDate",
		type: "dateTime",
		default: "",
		displayOptions: {
			show: {
				operation: [
					"crearCompra",
					"listarFacturasVentasPorID",
					"listarFacturasVenta",
					"listarFacturasCobros",
					"listarPedidosVenta",
					"listarPedidosVentaFiltrados",
					"listarOrdenesCompra",
					"listarCobros",
					"listarCompras",
					"crearVenta",
					"listarOrdenesCompra",
					"estadisticaVentaRanking",
				],
			},
		},
	},
	{
		displayName: "Fecha Hasta",
		name: "endDate",
		type: "dateTime",
		default: "",
		displayOptions: {
			show: {
				operation: [
					"listarFacturasVentasPorID",
					"listarFacturasVenta",
					"listarFacturasCobros",
					"listarPedidosVenta",
					"listarPedidosVentaFiltrados",
					"listarOrdenesCompra",
					"listarCobros",
					"listarCompras",
					"listarOrdenesCompra",
					"estadisticaVentaRanking",
				],
			},
		},
	},
	{
		displayName: "Fecha Documento",
		name: "documentDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Parametro fecha del body para las solicitudes",
		displayOptions: {
			show: {
				operation: [
					"crearRemitoVenta",
					"listarProductosDisponibles",
					"crearRemitoCompra",
					"listarPromocionesComercialesCliente",
					"crearCompra",
					"crearPedidoVenta",
					"crearOrdenCompra",
					"listarPromociones",
					"consultarPrecioProducto",
				],
			},
		},
	},
	{
		displayName: "Fecha Entrega",
		name: "deliveryDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Fecha de entrega",
		displayOptions: {
			show: { operation: ["crearOrdenCompra", "crearRemitoCompra", "crearRemitoVenta"] },
		},
	},
	{
		displayName: "Fecha Embarque",
		name: "shipmentDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Fecha de embarque",
		displayOptions: {
			show: { operation: ["crearRemitoVenta"] },
		},
	},
	{
		displayName: "Fecha De Imputacion",
		name: "indictmentDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Fecha de imputación",
		displayOptions: {
			show: { operation: ["crearRemitoVenta", "crearMovimientoStock"] },
		},
	},
	{
		displayName: "Fecha Vencimiento",
		name: "dueDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Fecha de vencimiento",
		displayOptions: {
			show: { operation: ["crearOrdenCompra", "crearRemitoCompra"] },
		},
	},
	{
		displayName: "Tipo De Ranking",
		name: "tipoDeRanking",
		type: "options",
		default: "none",
		description: "Tipo de ranking a filtrar",
		options: [
			{
				name: "Ninguno",
				value: "none",
			},
			{
				name: "Clientes",
				value: "esRankingClientes",
			},
			{
				name: "Artículos",
				value: "esRankingArticulos",
			},
			{
				name: "Vendedores",
				value: "esRankingVendedores",
			},
		],
		displayOptions: {
			show: { operation: ["estadisticaVentaRanking"] },
		},
	},
	{
		displayName: "Ordenar Ascendentemente",
		name: "orderAsc",
		type: "boolean",
		default: false,
		description: "Whether to order the sales statistics in ascending mode",
		displayOptions: {
			show: { operation: ["estadisticaVentaRanking"] },
		},
	},

	{
		displayName: "Vendedor ID",
		name: "vendedorID",
		type: "number",
		required: true,
		default: 0,
		description: "ID del vendedor utilizado para generar ventas",
		displayOptions: {
			show: {
				operation: ["crearPedidoVenta"],
			},
		},
	},
	{
		displayName: "Tipo De Orden",
		name: "ventaRankingOrderBy",
		type: "options",
		default: "CantidadUnidadNivel0",
		description: "Tipo de orden para obtener el ranking",
		options: [
			{
				name: "Cantidad Unidad Nivel 0",
				value: "CantidadUnidadNivel0",
			},
			{
				name: "Cantidad Unidad Nivel 1",
				value: "CantidadUnidadNivel1",
			},
			{
				name: "Cantidad Unidad Nivel 2",
				value: "CantidadUnidadNivel2",
			},
			{
				name: "Importe Total Final",
				value: "ImporteTotalFinal",
			},
			{
				name: "Importe Total Neto",
				value: "ImporteTotalNeto",
			},
		],
		displayOptions: {
			show: { operation: ["estadisticaVentaRanking"] },
		},
	},
	{
		displayName: "Fecha De Entrega",
		name: "deliveryDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Parametro fecha del body para las solicitudes",
		displayOptions: {
			show: { operation: ["crearPedidoVenta"] },
		},
	},
	{
		displayName: "Bonificación",
		name: "idBonificacion",
		type: "number",
		required: true,
		default: 0,
		description: "ID de la bonificación",
		displayOptions: {
			show: { operation: ["crearPedidoVenta", "crearVenta", "crearCliente"] },
		},
	},
	{
		displayName: "Turno De Entrega",
		name: "turnoEntrega",
		type: "string",
		required: true,
		default: "",
		description: "ID del turno de entrega",
		displayOptions: {
			show: { operation: ["crearPedidoVenta", "crearOrdenCompra", "crearRemitoCompra", "crearRemitoVenta"] },
		},
	},
	{
		displayName: "Fecha Modificación Desde",
		name: "dateModified",
		type: "dateTime",
		default: "",
		displayOptions: { show: { operation: ["listarProductosDisponibles"] } },
	},
	// {
	// 	displayName: 'Fecha Modificación Imagen Desde',
	// 	name: 'dateModifiedImage',
	// 	type: 'dateTime',
	// 	default: '',
	// 	displayOptions: { show: { operation: ['articulo'] } },
	// },
	{
		displayName: "Fecha Precio Actualizado Hasta",
		name: "priceDateModified",
		type: "dateTime",
		default: "",
		displayOptions: {
			show: { operation: ["consultarSaldoCliente", "verDetalleSaldoCliente"] },
		},
	},
	{
		displayName: "Forma De Pago Proveedor",
		name: "formaPagoProveedor",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "ID Del Chofer",
		name: "choferId",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearRemitoVenta"] } },
	},
	{
		displayName: "ID",
		name: "id",
		required: true,
		type: "string",
		default: "",
		placeholder: "Ej. 27231",
		description: "Identificador unico con el cual hacer solicitudes a la API",
		displayOptions: {
			show: { operation: ["verDetallePedidoVenta", "verDetalleRegimenEspecial"] },
		},
	},
	{
		displayName: "ID Articulos",
		name: "articleId",
		type: "string",
		default: "",
		placeholder: "1467",
		displayOptions: {
			show: {
				operation: [
					"descargarImagenesProductos",
					"buscarProductoPorCodigo",
					"buscarProductoEnSucursal",
					"consultarPrecioProducto",
					"listarProductosPorSucursal",
					"crearMovimientoStock",
				],
			},
		},
	},
	{
		displayName: "ID Bonificacion",
		name: "bonificacion",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearVenta"] } },
	},
	{
		displayName: "Ubicacion Articulo",
		name: "ubicacionArticulo",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearMovimientoStock"] } },
	},
	{
		displayName: "ID De Cobro",
		name: "idCobro",
		required: true,
		type: "number",
		default: 0,
		description: "ID del cobro",
		displayOptions: { show: { operation: ["listarCobros"] } },
	},
	{
		displayName: "ID De La Compra",
		name: "idCompra",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["listarCompras", "verDetalleOrdenCompra"] } },
	},
	{
		displayName: "ID Del Estado",
		name: "statusId",
		type: "number",
		default: false,
		description: "Número del estado del pedido",
		displayOptions: { show: { operation: ["listarPedidosVenta", "listarOrdenesCompra", "listarPedidosVentaFiltrados", "listarPedidosVenta"] } },
	},
	{
		displayName: "ID Del Operador Compra",
		name: "idOperadorCompra",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "ID Del Proveedor",
		name: "idProveedor",
		type: "number",
		default: "",
		placeholder: "2",
		description: "ID Del proveedor de la compra",
		displayOptions: { show: { operation: ["crearCompra"] } },
	},
	{
		displayName: "ID Del Tipo De Comprobante",
		name: "idTipoComprobante",
		type: "number",
		default: "",
		placeholder: "1",
		description: "ID del tipo de comprobante de la factura",
		displayOptions: { show: { operation: ["crearCompra", "listarFacturasVenta", "crearVenta"] } },
	},
	{
		displayName: "ID Del Tipo De Comprobante",
		name: "idTipoComprobante",
		type: "number",
		default: "",
		placeholder: "1",
		description: "ID del tipo de comprobante de la venta",
		displayOptions: { show: { operation: ["listarFacturasVenta"] } },
	},
	{
		displayName: "ID Cuenta Corriente",
		name: "cuentaCorrienteId",
		type: "number",
		default: "",
		placeholder: "1",
		description: "ID del cliente cuenta corriente del comprobante de venta",
		displayOptions: { show: { operation: ["listarFacturasVenta"] } },
	},
	{
		displayName: "ID Del Vendedor",
		name: "idVendedor",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearVenta", "listarFacturasVenta", "crearRemitoVenta"] } },
	},
	{
		displayName: "ID De La Venta",
		name: "ventaId",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["listarFacturasVenta", "listarPedidosVenta", "listarFacturasVentasPorID"] } },
	},
	{
		displayName: "ID De La Sucursal",
		name: "sucursalId",
		type: "number",
		default: "",
		displayOptions: { show: { operation: [] } },
	},
	{
		displayName: "Incluir Pedidos Anulados",
		name: "incluirAnulados",
		type: "boolean",
		default: false,
		displayOptions: { show: { operation: ["listarFacturasVenta", "listarPedidosVenta"] } },
	},
	{
		displayName: "ID Del Canal De Venta",
		name: "canalVentaId",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["listarFacturasVenta"] } },
	},
	{
		displayName: "ID De La Division Empresa",
		name: "divisionEmpresaId",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["listarFacturasVenta"] } },
	},
	{
		displayName: "ID Usuario Creador",
		name: "usuarioCreadorId",
		type: "number",
		description: "ID Del usuario que creo el comprobante de venta",
		default: "",
		displayOptions: { show: { operation: ["listarFacturasVenta", "listarPedidosVenta"] } },
	},
	{
		displayName: "ID Del Transporte",
		name: "transporteId",
		type: "number",
		description: "ID del transporte asociado al comprobante de venta",
		default: "",
		displayOptions: { show: { operation: ["listarFacturasVenta", "listarPedidosVenta"] } },
	},
	{
		displayName: "ID Pais",
		name: "idPais",
		type: "string",
		default: "",
		description: "ID del país por la cual se buscarán las provincias",
		displayOptions: { show: { operation: ["listarProvincias", "crearProveedor", "crearCliente"] } },
	},
	{
		displayName: "ID Provincia",
		name: "idProvincia",
		type: "string",
		default: "",
		description: "ID de la provincia por la cual se buscarán la información",
		displayOptions: { show: { operation: ["listarMunicipios", "crearProveedor", "crearCliente"] } },
	},
	{
		displayName: "ID Sucursal Física",
		name: "idSucursalFisica",
		type: "number",
		default: "",
		description: "The ID of the physical branch to filter stock (optional)",
		displayOptions: {
			show: {
				operation: [
					"crearMovimientoStock",
					"crearMovimientoStock",
					"crearRemitoVenta",
					"crearRemitoCompra",
					"buscarProductoEnSucursal",
					"crearCompra",
					"crearOrdenCompra",
					"listarProductosPorSucursal",
					"listarFacturasVenta",
					"listarPedidosVenta",
				],
			},
		},
	},
	{
		displayName: "ID Valor Efectivo",
		name: "idValorEfectivo",
		type: "number",
		default: 0,
		displayOptions: { show: { esContado: [true] } },
	},
	{
		displayName: "ID De La Zona",
		name: "idZona",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearProveedor", "crearCliente"] } },
	},
	{
		displayName: "ID del descuento del proveedor",
		name: "idDescuentoProveedor",
		type: "number",
		default: "",
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "Importe",
		name: "importeValorEfectivo",
		type: "number",
		default: 0,
		displayOptions: { show: { esContado: [true] } },
	},
	{
		displayName: "Información De Envío",
		name: "envio",
		required: true,
		type: "json",
		default: {},
		description: "Shipping info from the order",
		displayOptions: { show: { operation: ["registrarCobro"] } },
	},
	{
		displayName: "Lista ID",
		name: "idList",
		type: "number",
		default: "",
		description: "ID de la lista para buscar los precios de los articulos",
		displayOptions: { show: { operation: ["consultarPrecioProducto", "crearVenta", "estadisticaVentaRanking"] } },
	},
	{
		displayName: "Letra Del Documento De La Compra",
		name: "letraDocumento",
		type: "string",
		default: "",
		placeholder: "A",
		description: "Letra del documento de la compra de la factura",
		displayOptions: { show: { operation: ["crearCompra", "crearOrdenCompra", "crearRemitoCompra", "crearRemitoVenta"] } },
	},
	// {
	// 	displayName: 'Migración Completa',
	// 	name: 'migracionCompleta',
	// 	type: 'boolean',
	// 	default: false,
	// 	description: 'Whether complete articles migration or partial',
	// 	displayOptions: { show: { operation: ['articulo'] } },
	// },
	{
		displayName: "Nombre Del Tipo De Comprobante",
		name: "nombreTipoComprobante",
		type: "string",
		default: "",
		placeholder: "Factura de compras",
		description: "Nombre del tipo de comprobante de la factura",
		displayOptions: { show: { operation: ["crearCompra"] } },
	},
	{
		displayName: "Nombre Del Articulo",
		name: "nombreArticulo",
		type: "string",
		default: "",
		placeholder: "Alfajores",
		displayOptions: { show: { operation: ["buscarProductos", "listarProductosPorSucursal"] } },
		description: "El nombre del producto a buscar",
	},
	{
		displayName: "Numero Del Documento De La Compra",
		name: "numeroFactura",
		type: "number",
		default: "",
		placeholder: "1",
		description: "Numero del documento de la compra de la factura",
		displayOptions: { show: { operation: ["crearCompra", "crearOrdenCompra", "crearRemitoCompra", "crearRemitoVenta"] } },
	},
	{
		displayName: "Observaciones",
		name: "observacionesValorEfectivo",
		type: "string",
		default: "",
		displayOptions: { show: { esContado: [true] } },
	},
	{
		displayName: "Proveedor ID",
		name: "proveedorId",
		type: "number",
		required: true,
		default: "",
		description: "ID del proveedor usado para buscar dentro del sistema",
		displayOptions: { show: { operation: ["crearOrdenCompra", "buscarProveedor", "listarOrdenesCompra", "crearRemitoCompra"] } },
	},
	{
		displayName: "Punto De Venta",
		name: "puntoDeVenta",
		type: "number",
		default: "",
		placeholder: "1",
		description: "Numero del punto de venta del documento",
		displayOptions: { show: { operation: ["crearOrdenCompra", "crearVenta", "crearCompra", "crearRemitoCompra", "crearRemitoVenta"] } },
	},
	{
		displayName: "Razón Social",
		name: "razonSocial",
		type: "string",
		default: "",
		description: "Razón social del cliente para buscar",
		displayOptions: {
			show: { operation: ["buscarContribuyente", "buscarClientes", "crearProveedor", "crearPedidoVenta", "listarProveedores", "crearOrdenCompra", "crearCliente"] },
		},
	},
	{
		displayName: "Cantidad De Items",
		name: "cantidadDeItems",
		type: "number",
		default: 1,
		displayOptions: {
			show: { operation: ["estadisticaVentaRanking"] },
		},
	},
	{
		displayName: "Rubro ID",
		name: "rubroId",
		type: "string",
		default: "",
		description: "ID Rubros used to search the articles",
		displayOptions: { show: { operation: ["estadisticaVentaRanking", "listarProductosPorSucursal", "listarSubRubros"] } },
	},
	{
		displayName: "SKU",
		name: "sku",
		type: "string",
		default: "",
		required: true,
		description: "The SKU (product code) to search for",
		displayOptions: { show: { operation: ["buscarProductoPorCodigo"] } },
	},
	{
		displayName: "Sub-Rubros IDs",
		name: "idsSubRubros",
		type: "string",
		default: "",
		description: "Client ID used to search the articles",
		displayOptions: { show: { operation: ["listarCategorias", "listarProductosPorSucursal"] } },
	},
	{
		displayName: "Sucursales Físicas - IDs Lista",
		name: "branchOfficeIds",
		type: "string",
		required: true,
		default: "7345",
		description: "Physical branch ID separated by comma",
		displayOptions: { show: { operation: ["consultarStock"] } },
	},
	{
		displayName: "Ultima Modificacion Imagenes",
		name: "lastModifiedImg",
		type: "json",
		required: true,
		default: "",
		displayOptions: { show: { operation: ["sincronizarImagenes"] } },
	},
	{
		displayName: "Usuario",
		name: "username",
		type: "string",
		default: "",
		displayOptions: { show: { operation: ["verificarCredencialesOperador", "listarOperadoresMoviles"] } },
	},
	{
		displayName: "Código",
		name: "codigo",
		type: "number",
		default: "",
		displayOptions: {
			show: {
				operation: ["listarProveedores"],
			},
		},
	},
	{
		displayName: "Correo",
		name: "email",
		type: "string",
		placeholder: "name@email.com",
		default: "",
		displayOptions: {
			show: {
				operation: ["listarOperadoresMoviles"],
			},
		},
	},
	{
		displayName: "ID Marca Articulo",
		name: "IdMarcaArticulo",
		type: "string",
		placeholder: "3",
		default: "",
		displayOptions: {
			show: {
				operation: ["listarProductosPorSucursal"],
			},
		},
	},
	{
		displayName: "ID Categoria Articulo",
		name: "IdCategoriaArticulo",
		type: "string",
		placeholder: "3",
		default: "",
		displayOptions: {
			show: {
				operation: ["listarProductosPorSucursal"],
			},
		},
	},
];

export const CentumFields: INodeProperties[] = [...getArticulo];

export const HttpOptions: INodeProperties[] = [
	{
		displayName: "Ajustes HTTP",
		name: "httpSettings",
		type: "collection",
		placeholder: "Configuración avanzada",
		default: {},
		options: [
			{
				displayName: "Paginación",
				name: "pagination",
				type: "options",
				options: [
					{
						name: "Paginación Personalizada",
						value: "custom",
						description: "Permite definir la cantidad de ítems por página",
					},
					{
						name: "All",
						value: "all",
						description: "Trae todos los ítems paginando internamente sin opción de modificar cantidad por página ni intervalo",
					},
				],
				default: "custom",
				description: "Controla cómo se solicita la información paginada",
			},
			{
				displayName: "Ítems Por Página",
				name: "cantidadItemsPorPagina",
				type: "number",
				default: 100,
				typeOptions: {
					minValue: 1,
				},
				displayOptions: {
					show: {
						pagination: ["custom"],
					},
				},
				description: "Cantidad de ítems a solicitar por página (solo para modo personalizado)",
			},
			{
				displayName: "Intervalo Por Pagina(ms)",
				name: "intervaloPagina",
				type: "number",
				default: 1000,
				typeOptions: {
					minValue: 500,
				},
				displayOptions: {
					show: {
						pagination: ["custom"],
					},
				},
				description: "Intervalo de tiempo entre cada solicitud (En milisegundos)",
			},
			{
				displayName: "Número De Página Inicial",
				name: "numeroPagina",
				type: "number",
				default: 1,
				typeOptions: {
					minValue: 1,
				},
				displayOptions: {
					show: {
						pagination: ["custom"],
					},
				},
				description: "Número de página desde donde comenzar la paginación (por defecto comienza desde la página 1)",
			},
		],
		displayOptions: {
			show: {
				operation: ["listarClientes", "listarTodosLosProductos"],
			},
		},
	},
	{
		displayName: "Debug Options",
		name: "debugSettings",
		type: "collection",
		placeholder: "Advanced Options",
		default: {},
		options: [
			{
				displayName: "Enable Debug Logging",
				name: "enableDebugLogging",
				type: "boolean",
				default: false,
				description: "Whether to log request and response data for debugging",
			},
			{
				displayName: "Endpoint Filter",
				name: "debugEndpointContains",
				type: "string",
				default: "",
				placeholder: "/Ventas/FiltrosVentaConsulta",
				description: "Only log requests whose URL contains this value",
				displayOptions: {
					show: {
						enableDebugLogging: [true],
					},
				},
			},
			{
				displayName: "Max Logged Body Length",
				name: "debugMaxBodyLength",
				type: "number",
				default: 5000,
				typeOptions: {
					minValue: 100,
				},
				description: "Maximum number of characters to include in logged request or response bodies",
				displayOptions: {
					show: {
						enableDebugLogging: [true],
					},
				},
			},
		],
	},
];
