import { INodeProperties } from 'n8n-workflow';
import { CentumOperations, operationDisplayNames, resourceDisplayNames } from './CentumOperations';

export { CentumOperations, operationDisplayNames, resourceDisplayNames };

const fieldDefinitions: INodeProperties[] = [
	{
		displayName: 'Active',
		name: 'active',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: { operation: ['createSupplier', 'listSuppliers'] },
		},
	},
	{
		displayName: 'Articles',
		name: 'article',
		required: true,
		type: 'json',
		default: {},
		displayOptions: {
			show: {
				operation: [
					'registerPayment',
					'createSalesOrder',
					'createPurchaseOrder',
					'createPurchaseDeliveryNote',
				],
			},
		},
	},
	{
		displayName: 'Articles',
		name: 'articlesCollection',
		type: 'json',
		placeholder: '[{ "ID": 1234, "Quantity": 10 }, {"ID": 4567, "Quantity": 5}]',
		default: [],
		description: 'List of articles as a JSON array with ID or Code and Quantity',
		displayOptions: {
			show: { operation: ['createPurchase', 'createSale', 'createSalesDeliveryNote'] },
		},
	},
	{
		displayName: 'Cash Installment Count',
		name: 'cashValueInstallmentCount',
		type: 'number',
		default: 0,
		displayOptions: { show: { isCashSale: [true] } },
	},
	{
		displayName: 'Income Tax Category',
		name: 'incomeTaxCategoryId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSupplier'] } },
	},
	{
		displayName: 'Supplier Class',
		name: 'supplierClassId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSupplier'] } },
	},
	{
		displayName: 'Customer',
		name: 'customer',
		required: true,
		type: 'json',
		default: {},
		displayOptions: {
			show: { operation: ['registerPayment'] },
		},
	},
	{
		displayName: 'Delivery Date From',
		name: 'fromDeliveryDate',
		type: 'dateTime',
		default: '',
		displayOptions: {
			show: { operation: ['listPurchaseOrders'] },
		},
	},
	{
		displayName: 'Delivery Date To',
		name: 'sinceDeliveryDate',
		type: 'dateTime',
		default: '',
		displayOptions: {
			show: { operation: ['listPurchaseOrders'] },
		},
	},
	{
		displayName: 'Customer ID',
		name: 'customerId',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Enter customer ID',
		description: 'Customer used by the selected operation',
		displayOptions: {
			show: {
				operation: [
					'createPurchase',
					'listAvailableProducts',
					'getCustomerBalance',
					'getCustomerBalanceDetails',
					'listSalesInvoices',
					'listPaymentInvoices',
					'listCustomerCommercialPromotions',
					'listSalesOrders',
					'listPurchaseOrders',
					'listPayments',
					'listPurchases',
					'createSale',
					'listFilteredSalesOrders',
					// "getProductPrice",
					'createSalesDeliveryNote',
					'createPurchaseDeliveryNote',
				],
			},
		},
	},
	{
		displayName: 'Article Code',
		name: 'articleCode',
		type: 'string',
		default: '',
		placeholder: 'ART-001,ART-002',
		description: 'Article code to search for. Separate multiple values with a comma.',
		displayOptions: {
			show: {
				operation: ['getProductByCode', 'searchProducts'],
			},
		},
	},
	{
		displayName: 'Customer Code',
		name: 'customerCode',
		type: 'string',
		default: '',
		typeOptions: { minValue: 1 },
		placeholder: 'Example: 1507',
		description: 'Customer code to search for',
		displayOptions: {
			show: {
				operation: ['searchCustomers', 'createSalesOrder'],
			},
		},
	},
	{
		displayName: 'Voucher Code',
		name: 'voucherCode',
		type: 'string',
		default: '',
		placeholder: 'Purchase code (FCC)',
		description: 'Purchase voucher code',
		displayOptions: { show: { operation: ['createPurchase'] } },
	},
	{
		displayName: 'Sales Condition',
		name: 'salesConditionId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSale', 'createCustomer'] } },
	},
	{
		displayName: 'Payment Condition',
		name: 'paymentConditionId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSupplier'] } },
	},
	{
		displayName: 'VAT Condition ID',
		name: 'vatConditionId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSupplier', 'createCustomer'] } },
	},
	{
		displayName: 'Exchange Rate',
		name: 'cashValueExchangeRate',
		type: 'number',
		default: 0,
		displayOptions: { show: { isCashSale: [true] } },
	},
	{
		displayName: 'JSON Body',
		name: 'jsonBody',
		type: 'json',
		required: true,
		default: '{}',
		displayOptions: {
			show: {
				operation: ['updateCustomer', 'createTaxpayerCustomer'],
			},
		},
		description: 'JSON object sent to the API to update a customer or create a taxpayer customer',
	},
	{
		displayName: 'CUIT',
		name: 'cuit',
		type: 'string',
		default: '',
		placeholder: 'Enter the CUIT...',
		displayOptions: {
			show: {
				operation: [
					'createSupplier',
					'createCustomer',
					'searchTaxpayerCustomer',
					'createTaxpayerCustomer',
					'searchCustomerByCuit',
					'searchCustomers',
					'listSuppliers',
				],
			},
		},
	},
	{
		displayName: 'Image Data',
		name: 'dataImg',
		type: 'json',
		required: true,
		default: {},
		displayOptions: { show: { operation: ['syncImages'] } },
	},
	{
		displayName: 'Day of Week',
		name: 'weekday',
		type: 'number',
		default: 0,
		description: 'Weekday number used to filter applied promotions (0 is Monday)',
		displayOptions: { show: { operation: ['listCustomerCommercialPromotions'] } },
	},
	// {
	// 	displayName: 'DNI',
	// 	name: 'dni',
	// 	type: 'string',
	// 	default: '',
	// 	displayOptions: { show: { operation: ['createCustomer'] } },
	// },
	{
		displayName: 'Cash Sale',
		name: 'isCashSale',
		type: 'boolean',
		default: false,
		displayOptions: { show: { operation: ['createSale'] } },
	},
	{
		displayName: 'Date From',
		name: 'startDate',
		type: 'dateTime',
		default: '',
		displayOptions: {
			show: {
				operation: [
					'createPurchase',
					'listSalesInvoicesById',
					'listSalesInvoices',
					'listPaymentInvoices',
					'listSalesOrders',
					'listFilteredSalesOrders',
					'listPurchaseOrders',
					'listPayments',
					'listPurchases',
					'createSale',
					'listPurchaseOrders',
					'getSalesRanking',
				],
			},
		},
	},
	{
		displayName: 'Date To',
		name: 'endDate',
		type: 'dateTime',
		default: '',
		displayOptions: {
			show: {
				operation: [
					'listSalesInvoicesById',
					'listSalesInvoices',
					'listPaymentInvoices',
					'listSalesOrders',
					'listFilteredSalesOrders',
					'listPurchaseOrders',
					'listPayments',
					'listPurchases',
					'listPurchaseOrders',
					'getSalesRanking',
				],
			},
		},
	},
	{
		displayName: 'Document Date',
		name: 'documentDate',
		type: 'dateTime',
		required: true,
		default: undefined,
		description: 'Date body parameter used for the request',
		displayOptions: {
			show: {
				operation: [
					'createSalesDeliveryNote',
					'listAvailableProducts',
					'createPurchaseDeliveryNote',
					'listCustomerCommercialPromotions',
					'createPurchase',
					'createSalesOrder',
					'createPurchaseOrder',
					'listPromotions',
				],
			},
		},
	},
	{
		displayName: 'Delivery Date',
		name: 'deliveryDate',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'Document delivery date',
		displayOptions: {
			show: {
				operation: [
					'createPurchaseOrder',
					'createPurchaseDeliveryNote',
					'createSalesDeliveryNote',
					'createSalesOrder',
				],
			},
		},
	},
	{
		displayName: 'Shipment Date',
		name: 'shipmentDate',
		type: 'dateTime',
		required: true,
		default: undefined,
		displayOptions: {
			show: { operation: ['createSalesDeliveryNote'] },
		},
	},
	{
		displayName: 'Posting Date',
		name: 'indictmentDate',
		type: 'dateTime',
		required: true,
		default: undefined,
		displayOptions: {
			show: { operation: ['createSalesDeliveryNote', 'createStockMovement'] },
		},
	},
	{
		displayName: 'Due Date',
		name: 'dueDate',
		type: 'dateTime',
		required: true,
		default: undefined,
		displayOptions: {
			show: { operation: ['createPurchaseOrder', 'createPurchaseDeliveryNote'] },
		},
	},
	{
		displayName: 'Ranking Type',
		name: 'rankingType',
		type: 'options',
		default: 'none',
		description: 'Ranking type to filter by',
		options: [
			{
				name: 'None',
				value: 'none',
			},
			{
				name: 'Customers',
				value: 'customers',
			},
			{
				name: 'Articles',
				value: 'articles',
			},
			{
				name: 'Sellers',
				value: 'sellers',
			},
		],
		displayOptions: {
			show: { operation: ['getSalesRanking'] },
		},
	},
	{
		displayName: 'Sort Ascending',
		name: 'orderAsc',
		type: 'boolean',
		default: false,
		description: 'Whether to order the sales statistics in ascending mode',
		displayOptions: {
			show: { operation: ['getSalesRanking'] },
		},
	},

	{
		displayName: 'Seller ID',
		name: 'salesOrderSellerId',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Enter seller ID',
		description: 'Seller used to create the sales order',
		displayOptions: {
			show: {
				operation: ['createSalesOrder'],
			},
		},
	},
	{
		displayName: 'Sort Type',
		name: 'salesRankingOrderBy',
		type: 'options',
		default: 'quantityUnitLevel0',
		description: 'Sort type used to generate the ranking',
		options: [
			{
				name: 'Final Total Amount',
				value: 'finalTotalAmount',
			},
			{
				name: 'Net Total Amount',
				value: 'netTotalAmount',
			},
			{
				name: 'Quantity Unit Level 0',
				value: 'quantityUnitLevel0',
			},
			{
				name: 'Quantity Unit Level 1',
				value: 'quantityUnitLevel1',
			},
			{
				name: 'Quantity Unit Level 2',
				value: 'quantityUnitLevel2',
			},
		],
		displayOptions: {
			show: { operation: ['getSalesRanking'] },
		},
	},
	{
		displayName: 'Discount ID',
		name: 'discountId',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Enter discount ID',
		description: 'Discount ID',
		displayOptions: {
			show: { operation: ['createSalesOrder', 'createSale', 'createCustomer'] },
		},
	},
	{
		displayName: 'Delivery Time Slot ID',
		name: 'deliveryTimeSlotId',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Enter delivery time slot ID',
		description: 'Delivery time slot ID',
		displayOptions: {
			show: {
				operation: [
					'createSalesOrder',
					'createPurchaseOrder',
					'createPurchaseDeliveryNote',
					'createSalesDeliveryNote',
				],
			},
		},
	},
	{
		displayName: 'Modified Date From',
		name: 'dateModified',
		type: 'dateTime',
		default: '',
		displayOptions: { show: { operation: ['listAvailableProducts'] } },
	},
	{
		displayName: 'Image Modified Date From',
		name: 'dateModifiedImage',
		type: 'dateTime',
		default: '',
		displayOptions: { show: { operation: ['listAvailableProducts'] } },
		description: 'Filter articles whose images were modified from this date',
	},
	{
		displayName: 'Price Updated Date To',
		name: 'priceDateModifiedTo',
		type: 'dateTime',
		default: '',
		displayOptions: {
			show: {
				operation: ['getCustomerBalance', 'getCustomerBalanceDetails', 'getProductPrice'],
			},
		},
	},
	{
		displayName: 'Price Updated Date From',
		name: 'priceDateModifiedFrom',
		type: 'dateTime',
		default: '',
		displayOptions: {
			show: { operation: ['getProductPrice'] },
		},
	},
	{
		displayName: 'Supplier Payment Method',
		name: 'supplierPaymentMethodId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSupplier'] } },
	},
	{
		displayName: 'Driver ID',
		name: 'driverId',
		type: 'string',
		default: '',
		placeholder: 'Enter driver ID',
		description: 'Driver used for the delivery note',
		displayOptions: {
			show: { operation: ['createPurchaseDeliveryNote', 'createSalesDeliveryNote'] },
		},
	},
	{
		displayName: 'Notes',
		name: 'notes',
		type: 'string',
		default: '',
		description: 'Additional notes for the purchase delivery note',
		displayOptions: {
			show: { operation: ['createPurchaseDeliveryNote'] },
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		required: true,
		type: 'string',
		default: '',
		placeholder: 'Example: 27231',
		description: 'Unique identifier used to make API requests',
		displayOptions: {
			show: { operation: ['getSalesOrderDetails', 'getSpecialTaxRegimeDetails'] },
		},
	},
	{
		displayName: 'Article IDs',
		name: 'articleId',
		type: 'string',
		default: '',
		placeholder: '1467',
		displayOptions: {
			show: {
				operation: [
					'downloadProductImages',
					'getProductByCode',
					'getProductInBranch',
					'getProductPrice',
					'listProductsByBranch',
					'createStockMovement',
				],
			},
		},
	},
	{
		displayName: 'Discount ID',
		name: 'saleDiscountId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSale'] } },
	},
	{
		displayName: 'Article Location',
		name: 'articleLocationId',
		required: true,
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createStockMovement'] } },
	},
	{
		displayName: 'Branch Section ID',
		name: 'branchSectionId',
		required: true,
		type: 'number',
		default: 0,
		displayOptions: {
			show: { operation: ['createStockMovement', 'getArticleLocationsBySection'] },
		},
	},
	{
		displayName: 'Payment ID',
		name: 'paymentId',
		required: true,
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['listPayments'] } },
	},
	{
		displayName: 'Purchase ID',
		name: 'purchaseId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['listPurchases', 'getPurchaseOrderDetails'] } },
	},
	{
		displayName: 'Status ID',
		name: 'statusId',
		type: 'string',
		default: '',
		placeholder: 'Enter status ID',
		description: 'Sales order status number',
		displayOptions: {
			show: {
				operation: [
					'listSalesOrders',
					'listPurchaseOrders',
					'listFilteredSalesOrders',
					'listSalesOrders',
				],
			},
		},
	},
	{
		displayName: 'Purchase Operator ID',
		name: 'purchaseOperatorId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSupplier'] } },
	},
	{
		displayName: 'Supplier ID',
		name: 'purchaseSupplierId',
		type: 'string',
		default: '',
		placeholder: 'Enter supplier ID',
		description: 'Supplier ID for the purchase',
		displayOptions: { show: { operation: ['createPurchase'] } },
	},
	{
		displayName: 'Voucher Type ID',
		name: 'voucherTypeId',
		type: 'string',
		default: '',
		placeholder: 'Enter voucher type ID',
		description: 'Invoice voucher type ID',
		displayOptions: { show: { operation: ['createPurchase', 'listSalesInvoices', 'createSale'] } },
	},
	{
		displayName: 'Current Account ID',
		name: 'currentAccountId',
		type: 'number',
		default: 0,
		placeholder: '1',
		description: 'Current-account customer ID for the sales voucher',
		displayOptions: { show: { operation: ['listSalesInvoices'] } },
	},
	{
		displayName: 'Seller ID',
		name: 'sellerId',
		type: 'string',
		default: '',
		placeholder: 'Enter seller ID',
		displayOptions: {
			show: { operation: ['createSale', 'listSalesInvoices', 'createSalesDeliveryNote'] },
		},
	},
	{
		displayName: 'Sale ID',
		name: 'saleId',
		type: 'number',
		default: 0,
		displayOptions: {
			show: {
				operation: ['listSalesInvoices', 'listSalesOrders', 'listSalesInvoicesById'],
			},
		},
	},
	{
		displayName: 'Branch ID',
		name: 'branchId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: [] } },
	},
	{
		displayName: 'Include Canceled Orders',
		name: 'includeCanceled',
		type: 'boolean',
		default: false,
		displayOptions: { show: { operation: ['listSalesInvoices', 'listSalesOrders'] } },
	},
	{
		displayName: 'Sales Channel ID',
		name: 'salesChannelId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['listSalesInvoices'] } },
	},
	{
		displayName: 'Business Division ID',
		name: 'businessDivisionId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['listSalesInvoices'] } },
	},
	{
		displayName: 'Created By User ID',
		name: 'createdByUserId',
		type: 'number',
		description: 'User ID that created the sales voucher',
		default: 0,
		displayOptions: { show: { operation: ['listSalesInvoices', 'listSalesOrders'] } },
	},
	{
		displayName: 'Transport ID',
		name: 'transportId',
		type: 'number',
		description: 'Transport ID associated with the sales voucher',
		default: 0,
		displayOptions: { show: { operation: ['listSalesInvoices', 'listSalesOrders'] } },
	},
	{
		displayName: 'Country ID',
		name: 'countryId',
		type: 'string',
		default: '',
		placeholder: 'Enter country ID',
		description: 'Country ID used to fetch provinces',
		displayOptions: { show: { operation: ['listProvinces', 'createSupplier', 'createCustomer'] } },
	},
	{
		displayName: 'Province ID',
		name: 'provinceId',
		type: 'string',
		default: '',
		placeholder: 'Enter province ID',
		description: 'Province ID used to fetch related information',
		displayOptions: {
			show: { operation: ['listMunicipalities', 'createSupplier', 'createCustomer'] },
		},
	},
	{
		displayName: 'Physical Branch ID',
		name: 'physicalBranchId',
		type: 'string',
		default: '',
		placeholder: 'Enter branch ID',
		description: 'The ID of the physical branch to filter stock (optional)',
		displayOptions: {
			show: {
				operation: [
					'createStockMovement',
					'createStockMovement',
					'createSalesDeliveryNote',
					'createPurchaseDeliveryNote',
					'getProductInBranch',
					'createPurchase',
					'createPurchaseOrder',
					'listProductsByBranch',
					'listSalesInvoices',
					'listSalesOrders',
				],
			},
		},
	},
	{
		displayName: 'Cash Value ID',
		name: 'cashValueId',
		type: 'number',
		default: 0,
		displayOptions: { show: { isCashSale: [true] } },
	},
	{
		displayName: 'Zone ID',
		name: 'zoneId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSupplier', 'createCustomer'] } },
	},
	{
		displayName: 'Supplier Discount ID',
		name: 'supplierDiscountId',
		type: 'number',
		default: 0,
		displayOptions: { show: { operation: ['createSupplier'] } },
	},
	{
		displayName: 'Amount',
		name: 'cashValueAmount',
		type: 'number',
		default: 0,
		displayOptions: { show: { isCashSale: [true] } },
	},
	{
		displayName: 'Shipping Information',
		name: 'shippingInfo',
		required: true,
		type: 'json',
		default: {},
		description: 'Shipping info from the order',
		displayOptions: { show: { operation: ['registerPayment'] } },
	},
	{
		displayName: 'Price List ID',
		name: 'priceListId',
		type: 'string',
		default: '',
		placeholder: 'Enter price list ID',
		description: 'Price list used to look up article prices',
		displayOptions: {
			show: { operation: ['getProductPrice', 'createSale', 'getSalesRanking'] },
		},
	},
	{
		displayName: 'Purchase Document Letter',
		name: 'documentLetter',
		type: 'string',
		default: '',
		placeholder: 'A',
		description: 'Purchase invoice document letter',
		displayOptions: {
			show: {
				operation: [
					'createPurchase',
					'createPurchaseOrder',
					'createPurchaseDeliveryNote',
					'createSalesDeliveryNote',
				],
			},
		},
	},
	{
		displayName: 'Full Migration',
		name: 'fullMigration',
		type: 'boolean',
		default: false,
		description: 'Whether to return only the first response without expanding group variants',
		displayOptions: { show: { operation: ['listAvailableProducts'] } },
	},
	{
		displayName: 'Voucher Type Name',
		name: 'voucherTypeName',
		type: 'string',
		default: '',
		placeholder: 'Purchase invoice',
		description: 'Invoice voucher type name',
		displayOptions: { show: { operation: ['createPurchase'] } },
	},
	{
		displayName: 'Article Name',
		name: 'articleName',
		type: 'string',
		default: '',
		placeholder: 'Chocolate Bars',
		displayOptions: { show: { operation: ['searchProducts', 'listProductsByBranch'] } },
		description: 'Name of the product to search for',
	},
	{
		displayName: 'Purchase Document Number',
		name: 'documentNumber',
		type: 'number',
		default: 0,
		placeholder: '1',
		description: 'Purchase invoice document number',
		displayOptions: {
			show: {
				operation: [
					'createPurchase',
					'createPurchaseOrder',
					'createPurchaseDeliveryNote',
					'createSalesDeliveryNote',
				],
			},
		},
	},
	{
		displayName: 'Notes',
		name: 'cashValueNotes',
		type: 'string',
		default: '',
		displayOptions: { show: { isCashSale: [true] } },
	},
	{
		displayName: 'Supplier ID',
		name: 'supplierId',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Enter supplier ID',
		description: 'Supplier ID used to search inside the system',
		displayOptions: {
			show: {
				operation: [
					'createPurchaseOrder',
					'searchSupplier',
					'listPurchaseOrders',
					'createPurchaseDeliveryNote',
				],
			},
		},
	},
	{
		displayName: 'Point of Sale',
		name: 'pointOfSale',
		type: 'number',
		default: 0,
		placeholder: '1',
		description: 'Document point-of-sale number',
		displayOptions: {
			show: {
				operation: [
					'createPurchaseOrder',
					'createSale',
					'createPurchase',
					'createPurchaseDeliveryNote',
					'createSalesDeliveryNote',
				],
			},
		},
	},
	{
		displayName: 'Business Name',
		name: 'businessName',
		type: 'string',
		default: '',
		description: 'Customer business name to search for',
		displayOptions: {
			show: {
				operation: [
					'searchTaxpayerCustomer',
					'searchCustomers',
					'createSupplier',
					'createSalesOrder',
					'listSuppliers',
					'createPurchaseOrder',
					'createCustomer',
				],
			},
		},
	},
	{
		displayName: 'Item Count',
		name: 'itemCount',
		type: 'number',
		default: 1,
		displayOptions: {
			show: { operation: ['getSalesRanking'] },
		},
	},
	{
		displayName: 'Group ID',
		name: 'groupId',
		type: 'string',
		default: '',
		description: 'Group ID used to search for articles',
		displayOptions: {
			show: {
				operation: ['getSalesRanking', 'listProductsByBranch', 'listSubgroups'],
			},
		},
	},
	// {
	// 	displayName: "SKU",
	// 	name: "sku",
	// 	type: "string",
	// 	default: "",
	// 	required: true,
	// 	description: "The SKU (product code) to search for",
	// 	displayOptions: { show: { operation: ["getProductByCode"] } },
	// },
	{
		displayName: 'Subgroup IDs',
		name: 'subgroupIds',
		type: 'string',
		default: '',
		description: 'Subgroup IDs used to search for articles',
		displayOptions: { show: { operation: ['listCategories', 'listProductsByBranch'] } },
	},
	{
		displayName: 'Physical Branches - ID List',
		name: 'branchOfficeIds',
		type: 'string',
		required: true,
		default: '7345',
		description: 'Physical branch ID separated by comma',
		displayOptions: { show: { operation: ['getStock'] } },
	},
	{
		displayName: 'Last Image Update',
		name: 'lastModifiedImg',
		type: 'json',
		required: true,
		default: {},
		displayOptions: { show: { operation: ['syncImages'] } },
	},
	{
		displayName: 'Username',
		name: 'username',
		type: 'string',
		default: '',
		displayOptions: {
			show: { operation: ['verifyOperatorCredentials', 'listMobileOperators'] },
		},
	},
	{
		displayName: 'Supplier Code',
		name: 'supplierCode',
		type: 'number',
		default: 0,
		displayOptions: {
			show: {
				operation: ['createSupplier', 'listSuppliers'],
			},
		},
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'name@email.com',
		default: '',
		displayOptions: {
			show: {
				operation: ['listMobileOperators'],
			},
		},
	},
	{
		displayName: 'Article Brand ID',
		name: 'articleBrandId',
		type: 'string',
		placeholder: '3',
		default: '',
		displayOptions: {
			show: {
				operation: ['listProductsByBranch'],
			},
		},
	},
	{
		displayName: 'Article Category ID',
		name: 'articleCategoryId',
		type: 'string',
		placeholder: '3',
		default: '',
		displayOptions: {
			show: {
				operation: ['listProductsByBranch'],
			},
		},
	},
	{
		displayName: 'Simplified Output',
		name: 'simplifiedOutput',
		type: 'boolean',
		default: false,
		description: 'Whether to return only the most useful top-level fields',
		displayOptions: {
			show: {
				operation: [
					'searchProducts',
					'getProductByCode',
					'listAvailableProducts',
					'listAllProducts',
					'getProductPrice',
					'listProductsByBranch',
					'getProductInBranch',
					'searchCustomers',
					'searchCustomerByCuit',
					'listCustomers',
					'getCustomerBalance',
					'getCustomerBalanceDetails',
					'listPaymentInvoices',
					'listSalesInvoices',
					'listSalesInvoicesById',
					'listCustomerCommercialPromotions',
					'searchTaxpayerCustomer',
					'listSalesVouchers',
					'listSalesOrders',
					'listFilteredSalesOrders',
					'getSalesRanking',
					'listPayments',
					'listPurchases',
					'listPurchaseVouchers',
					'listPurchaseOrders',
					'getPurchaseOrderDetails',
					'listSuppliers',
				],
			},
		},
	},
];

export const CentumFields: INodeProperties[] = [...fieldDefinitions];

export const HttpOptions: INodeProperties[] = [
	{
		displayName: 'HTTP Settings',
		name: 'httpSettings',
		type: 'collection',
		placeholder: 'Advanced configuration',
		default: {},
		options: [
			{
				displayName: 'Pagination',
				name: 'pagination',
				type: 'options',
				options: [
					{
						name: 'Custom Pagination',
						value: 'custom',
						description: 'Lets you define the number of items per page',
					},
					{
						name: 'All',
						value: 'all',
						description:
							'Fetch all items with internal pagination and without per-page or interval customization',
					},
				],
				default: 'custom',
				description: 'Controls how paginated data is requested',
			},
			{
				displayName: 'Items per Page',
				name: 'itemsPerPage',
				type: 'number',
				default: 100,
				typeOptions: {
					minValue: 1,
				},
				displayOptions: {
					show: {
						pagination: ['custom'],
					},
				},
				description: 'Number of items to request per page (custom mode only)',
			},
			{
				displayName: 'Page Interval (Ms)',
				name: 'pageInterval',
				type: 'number',
				default: 1000,
				typeOptions: {
					minValue: 500,
				},
				displayOptions: {
					show: {
						pagination: ['custom'],
					},
				},
				description: 'Time interval between requests in milliseconds',
			},
			{
				displayName: 'Starting Page Number',
				name: 'pageNumber',
				type: 'number',
				default: 1,
				typeOptions: {
					minValue: 1,
				},
				displayOptions: {
					show: {
						pagination: ['custom'],
					},
				},
				description: 'Page number where pagination should start (defaults to page 1)',
			},
		],
		displayOptions: {
			show: {
				operation: ['listCustomers', 'listAllProducts', 'listAvailableProducts'],
			},
		},
	},
	{
		displayName: 'Debug Options',
		name: 'debugSettings',
		type: 'collection',
		placeholder: 'Advanced Options',
		default: {},
		options: [
			{
				displayName: 'Enable Debug Logging',
				name: 'enableDebugLogging',
				type: 'boolean',
				default: false,
				description: 'Whether to log sanitized request metadata for debugging',
			},
			{
				displayName: 'Endpoint Filter',
				name: 'debugEndpointContains',
				type: 'string',
				default: '',
				placeholder: '/Ventas/FiltrosVentaConsulta',
				description: 'Only log requests whose URL contains this value',
				displayOptions: {
					show: {
						enableDebugLogging: [true],
					},
				},
			},
		],
	},
];
