import { INodeProperties } from "n8n-workflow";
import { CentumOperations } from "./CentumOperations";

export { CentumOperations };

const getArticulo: INodeProperties[] = [
	{
		displayName: "Activo",
		name: "active",
		type: "boolean",
		default: false,
		displayOptions: {
			show: { operation: ["crearProveedor", "listarProveedores"] },
		},
	},
	{
		displayName: "Articulos",
		name: "articulo",
		required: true,
		type: "json",
		default: {},
		displayOptions: {
			show: {
				operation: ["registrarCobro", "crearPedidoVenta", "crearOrdenCompra", "crearRemitoCompra"],
			},
		},
	},
	{
		displayName: "Artículos",
		name: "articlesCollection",
		type: "json",
		placeholder: '[{ "ID": 1234, "Cantidad": 10 }, {"ID": 4567, "Cantidad": 5}]',
		default: [],
		description: "Lista de artículos como arreglo JSON con ID o Codigo y Cantidad",
		displayOptions: {
			show: { operation: ["crearCompra", "crearVenta", "crearRemitoVenta"] },
		},
	},
	{
		displayName: "Cantidad De Cuotas Efectivo",
		name: "cantidadCuotasValorEfectivo",
		type: "number",
		default: 0,
		displayOptions: { show: { esContado: [true] } },
	},
	// {
	// 	displayName: 'Cantidad Por Página',
	// 	name: 'cantidadPorPagina',
	// 	type: 'number',
	// 	default: 50,
	// 	description: 'Cantidad de artículos por página',
	// 	displayOptions: { show: { operation: ['articulo'] } },
	// },
	{
		displayName: "Categoría De Impuestos A Las Ganancias",
		name: "categoriaImpuestosGanancias",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "Clase De Proveedor",
		name: "claseProveedor",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "Cliente",
		name: "cliente",
		required: true,
		type: "json",
		default: {},
		displayOptions: {
			show: { operation: ["registrarCobro"] },
		},
	},
	{
		displayName: "Fecha De Entrega Desde",
		name: "fromDeliveryDate",
		type: "dateTime",
		default: "",
		displayOptions: {
			show: { operation: ["listarOrdenesCompra"] },
		},
	},
	{
		displayName: "Fecha De Entrega Hasta",
		name: "sinceDeliveryDate",
		type: "dateTime",
		default: "",
		displayOptions: {
			show: { operation: ["listarOrdenesCompra"] },
		},
	},
	{
		displayName: "Cliente ID",
		name: "clienteId",
		type: "number",
		required: true,
		typeOptions: { maxValue: 9999999, minValue: 0, numberStepSize: 1 },
		default: 0,
		description: "Client ID used to search the articles",
		displayOptions: {
			show: {
				operation: [
					"crearCompra",
					"listarProductosDisponibles",
					"consultarSaldoCliente",
					"verDetalleSaldoCliente",
					"listarFacturasVenta",
					"listarFacturasCobros",
					"listarPromocionesComercialesCliente",
					"listarPedidosVenta",
					"listarOrdenesCompra",
					"listarCobros",
					"listarCompras",
					"crearVenta",
					"listarPedidosVentaFiltrados",
					// "consultarPrecioProducto",
					"crearRemitoVenta",
					"crearRemitoCompra",
				],
			},
		},
	},
	{
		displayName: "Codigo Artículo",
		name: "codigoArticulo",
		type: "string",
		default: "",
		placeholder: "ART-001,ART-002",
		description: 'Codigo del articulo a buscar. Separa con "," si necesitas mas de uno.',
		displayOptions: {
			show: {
				operation: ["buscarProductoPorCodigo", "buscarProductos"],
			},
		},
	},
	{
		displayName: "Codigo Cliente",
		name: "codigoCliente",
		type: "string",
		default: "",
		typeOptions: { minValue: 1 },
		placeholder: "Ej. 1507",
		description: "Codigo del cliente a buscar",
		displayOptions: {
			show: {
				operation: ["buscarClientes", "crearPedidoVenta"],
			},
		},
	},
	{
		displayName: "Código Del Comprobante",
		name: "codigoComprobante",
		type: "string",
		default: "",
		placeholder: "Codigo de la compra (FCC)",
		description: "Codigo del comprobante de la compra",
		displayOptions: { show: { operation: ["crearCompra"] } },
	},
	{
		displayName: "Condicion De Venta",
		name: "idCondicionVenta",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearVenta", "crearCliente"] } },
	},
	{
		displayName: "Condición De Pago",
		name: "condicionDePago",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "ID Condición IVA",
		name: "condicionIVA",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearProveedor", "crearCliente"] } },
	},
	{
		displayName: "Cotizacion",
		name: "cotizacionValorEfectivo",
		type: "number",
		default: 0,
		displayOptions: { show: { esContado: [true] } },
	},
	{
		displayName: "Cuerpo JSON",
		name: "cuerpoHTTP",
		type: "json",
		required: true,
		default: "{}",
		displayOptions: {
			show: {
				operation: ["actualizarCliente", "crearContribuyente"],
			},
		},
		description: "Objeto JSON enviado a la API para actualizar un cliente o crear un contribuyente",
	},
	{
		displayName: "CUIT",
		name: "cuit",
		type: "string",
		default: "",
		placeholder: "Ingresá el CUIT...",
		displayOptions: {
			show: {
				operation: ["crearProveedor", "crearCliente", "buscarContribuyente", "crearContribuyente", "buscarClientePorCuit", "buscarClientes", "listarProveedores"],
			},
		},
	},
	{
		displayName: "Datos Imagen",
		name: "dataImg",
		type: "json",
		required: true,
		default: {},
		displayOptions: { show: { operation: ["sincronizarImagenes"] } },
	},
	{
		displayName: "Dia De La Semana",
		name: "diaSemana",
		type: "number",
		default: 0,
		description: "Numero de la semana por el cual filtrar promociones aplicadas (0 es Lunes)",
		displayOptions: { show: { operation: ["listarPromocionesComercialesCliente"] } },
	},
	// {
	// 	displayName: 'DNI',
	// 	name: 'dni',
	// 	type: 'string',
	// 	default: '',
	// 	displayOptions: { show: { operation: ['crearCliente'] } },
	// },
	// {
	// 	displayName: 'Documento',
	// 	name: 'documentDate',
	// 	type: 'dateTime',
	// 	required: true,
	// 	default: undefined,
	// 	description: 'Parametro fecha del body para las solicitudes',
	// 	displayOptions: {
	// 		show: { operation: ['articulo', 'promocionesCliente', 'generarCompras'] },
	// 	},
	// },
	{
		displayName: "Es Contado",
		name: "esContado",
		type: "boolean",
		default: false,
		displayOptions: { show: { operation: ["crearVenta"] } },
	},
	{
		displayName: "Fecha Desde",
		name: "startDate",
		type: "dateTime",
		default: "",
		displayOptions: {
			show: {
				operation: [
					"crearCompra",
					"listarFacturasVentasPorID",
					"listarFacturasVenta",
					"listarFacturasCobros",
					"listarPedidosVenta",
					"listarPedidosVentaFiltrados",
					"listarOrdenesCompra",
					"listarCobros",
					"listarCompras",
					"crearVenta",
					"listarOrdenesCompra",
					"estadisticaVentaRanking",
				],
			},
		},
	},
	{
		displayName: "Fecha Hasta",
		name: "endDate",
		type: "dateTime",
		default: "",
		displayOptions: {
			show: {
				operation: [
					"listarFacturasVentasPorID",
					"listarFacturasVenta",
					"listarFacturasCobros",
					"listarPedidosVenta",
					"listarPedidosVentaFiltrados",
					"listarOrdenesCompra",
					"listarCobros",
					"listarCompras",
					"listarOrdenesCompra",
					"estadisticaVentaRanking",
				],
			},
		},
	},
	{
		displayName: "Fecha Documento",
		name: "documentDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Parametro fecha del body para las solicitudes",
		displayOptions: {
			show: {
				operation: [
					"crearRemitoVenta",
					"listarProductosDisponibles",
					"crearRemitoCompra",
					"listarPromocionesComercialesCliente",
					"crearCompra",
					"crearPedidoVenta",
					"crearOrdenCompra",
					"listarPromociones",
				],
			},
		},
	},
	{
		displayName: "Fecha Entrega",
		name: "deliveryDate",
		type: "dateTime",
		required: true,
		default: "",
		description: "Fecha de entrega del documento",
		displayOptions: {
			show: {
				operation: ["crearOrdenCompra", "crearRemitoCompra", "crearRemitoVenta", "crearPedidoVenta"],
			},
		},
	},
	{
		displayName: "Fecha Embarque",
		name: "shipmentDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Fecha de embarque",
		displayOptions: {
			show: { operation: ["crearRemitoVenta"] },
		},
	},
	{
		displayName: "Fecha De Imputacion",
		name: "indictmentDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Fecha de imputación",
		displayOptions: {
			show: { operation: ["crearRemitoVenta", "crearMovimientoStock"] },
		},
	},
	{
		displayName: "Fecha Vencimiento",
		name: "dueDate",
		type: "dateTime",
		required: true,
		default: undefined,
		description: "Fecha de vencimiento",
		displayOptions: {
			show: { operation: ["crearOrdenCompra", "crearRemitoCompra"] },
		},
	},
	{
		displayName: "Tipo De Ranking",
		name: "tipoDeRanking",
		type: "options",
		default: "none",
		description: "Tipo de ranking a filtrar",
		options: [
			{
				name: "Ninguno",
				value: "none",
			},
			{
				name: "Clientes",
				value: "esRankingClientes",
			},
			{
				name: "Artículos",
				value: "esRankingArticulos",
			},
			{
				name: "Vendedores",
				value: "esRankingVendedores",
			},
		],
		displayOptions: {
			show: { operation: ["estadisticaVentaRanking"] },
		},
	},
	{
		displayName: "Ordenar Ascendentemente",
		name: "orderAsc",
		type: "boolean",
		default: false,
		description: "Whether to order the sales statistics in ascending mode",
		displayOptions: {
			show: { operation: ["estadisticaVentaRanking"] },
		},
	},

	{
		displayName: "Vendedor ID",
		name: "vendedorID",
		type: "number",
		required: true,
		default: 0,
		description: "ID del vendedor utilizado para generar ventas",
		displayOptions: {
			show: {
				operation: ["crearPedidoVenta"],
			},
		},
	},
	{
		displayName: "Tipo De Orden",
		name: "ventaRankingOrderBy",
		type: "options",
		default: "CantidadUnidadNivel0",
		description: "Tipo de orden para obtener el ranking",
		options: [
			{
				name: "Cantidad Unidad Nivel 0",
				value: "CantidadUnidadNivel0",
			},
			{
				name: "Cantidad Unidad Nivel 1",
				value: "CantidadUnidadNivel1",
			},
			{
				name: "Cantidad Unidad Nivel 2",
				value: "CantidadUnidadNivel2",
			},
			{
				name: "Importe Total Final",
				value: "ImporteTotalFinal",
			},
			{
				name: "Importe Total Neto",
				value: "ImporteTotalNeto",
			},
		],
		displayOptions: {
			show: { operation: ["estadisticaVentaRanking"] },
		},
	},
	{
		displayName: "Bonificación",
		name: "idBonificacion",
		type: "number",
		required: true,
		default: 0,
		description: "ID de la bonificación",
		displayOptions: {
			show: { operation: ["crearPedidoVenta", "crearVenta", "crearCliente"] },
		},
	},
	{
		displayName: "Turno De Entrega",
		name: "turnoEntrega",
		type: "string",
		required: true,
		default: "",
		description: "ID del turno de entrega",
		displayOptions: {
			show: {
				operation: ["crearPedidoVenta", "crearOrdenCompra", "crearRemitoCompra", "crearRemitoVenta"],
			},
		},
	},
	{
		displayName: "Fecha Modificación Desde",
		name: "dateModified",
		type: "dateTime",
		default: "",
		displayOptions: { show: { operation: ["listarProductosDisponibles"] } },
	},
	{
		displayName: "Fecha Modificación Imagen Desde",
		name: "dateModifiedImage",
		type: "dateTime",
		default: "",
		displayOptions: { show: { operation: ["listarProductosDisponibles"] } },
		description: "Filtra artículos con imágenes modificadas desde esta fecha",
	},
	{
		displayName: "Fecha Precio Actualizado Hasta",
		name: "priceDateModifiedTo",
		type: "dateTime",
		default: "",
		displayOptions: {
			show: {
				operation: ["consultarSaldoCliente", "verDetalleSaldoCliente", "consultarPrecioProducto"],
			},
		},
	},
	{
		displayName: "Fecha Precio Actualizado Desde",
		name: "priceDateModifiedFrom",
		type: "dateTime",
		default: "",
		displayOptions: {
			show: { operation: ["consultarPrecioProducto"] },
		},
	},
	{
		displayName: "Forma De Pago Proveedor",
		name: "formaPagoProveedor",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "ID Del Chofer",
		name: "choferId",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearRemitoVenta"] } },
	},
	{
		displayName: "ID",
		name: "id",
		required: true,
		type: "string",
		default: "",
		placeholder: "Ej. 27231",
		description: "Identificador unico con el cual hacer solicitudes a la API",
		displayOptions: {
			show: { operation: ["verDetallePedidoVenta", "verDetalleRegimenEspecial"] },
		},
	},
	{
		displayName: "ID Articulos",
		name: "articleId",
		type: "string",
		default: "",
		placeholder: "1467",
		displayOptions: {
			show: {
				operation: [
					"descargarImagenesProductos",
					"buscarProductoPorCodigo",
					"buscarProductoEnSucursal",
					"consultarPrecioProducto",
					"listarProductosPorSucursal",
					"crearMovimientoStock",
				],
			},
		},
	},
	{
		displayName: "ID Bonificacion",
		name: "bonificacion",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearVenta"] } },
	},
	{
		displayName: "Ubicacion Articulo",
		name: "ubicacionArticulo",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearMovimientoStock"] } },
	},
	{
		displayName: "ID De Cobro",
		name: "idCobro",
		required: true,
		type: "number",
		default: 0,
		description: "ID del cobro",
		displayOptions: { show: { operation: ["listarCobros"] } },
	},
	{
		displayName: "ID De La Compra",
		name: "idCompra",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["listarCompras", "verDetalleOrdenCompra"] } },
	},
	{
		displayName: "ID Del Estado",
		name: "statusId",
		type: "number",
		default: 0,
		description: "Número del estado del pedido",
		displayOptions: {
			show: {
				operation: ["listarPedidosVenta", "listarOrdenesCompra", "listarPedidosVentaFiltrados", "listarPedidosVenta"],
			},
		},
	},
	{
		displayName: "ID Del Operador Compra",
		name: "idOperadorCompra",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "ID Del Proveedor",
		name: "idProveedor",
		type: "number",
		default: 0,
		placeholder: "2",
		description: "ID Del proveedor de la compra",
		displayOptions: { show: { operation: ["crearCompra"] } },
	},
	{
		displayName: "ID Del Tipo De Comprobante",
		name: "idTipoComprobante",
		type: "number",
		default: 0,
		placeholder: "1",
		description: "ID del tipo de comprobante de la factura",
		displayOptions: { show: { operation: ["crearCompra", "listarFacturasVenta", "crearVenta"] } },
	},
	{
		displayName: "ID Cuenta Corriente",
		name: "cuentaCorrienteId",
		type: "number",
		default: 0,
		placeholder: "1",
		description: "ID del cliente cuenta corriente del comprobante de venta",
		displayOptions: { show: { operation: ["listarFacturasVenta"] } },
	},
	{
		displayName: "ID Del Vendedor",
		name: "idVendedor",
		type: "number",
		default: 0,
		displayOptions: {
			show: { operation: ["crearVenta", "listarFacturasVenta", "crearRemitoVenta"] },
		},
	},
	{
		displayName: "ID De La Venta",
		name: "ventaId",
		type: "number",
		default: 0,
		displayOptions: {
			show: {
				operation: ["listarFacturasVenta", "listarPedidosVenta", "listarFacturasVentasPorID"],
			},
		},
	},
	{
		displayName: "ID De La Sucursal",
		name: "sucursalId",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: [] } },
	},
	{
		displayName: "Incluir Pedidos Anulados",
		name: "incluirAnulados",
		type: "boolean",
		default: false,
		displayOptions: { show: { operation: ["listarFacturasVenta", "listarPedidosVenta"] } },
	},
	{
		displayName: "ID Del Canal De Venta",
		name: "canalVentaId",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["listarFacturasVenta"] } },
	},
	{
		displayName: "ID De La Division Empresa",
		name: "divisionEmpresaId",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["listarFacturasVenta"] } },
	},
	{
		displayName: "ID Usuario Creador",
		name: "usuarioCreadorId",
		type: "number",
		description: "ID Del usuario que creo el comprobante de venta",
		default: 0,
		displayOptions: { show: { operation: ["listarFacturasVenta", "listarPedidosVenta"] } },
	},
	{
		displayName: "ID Del Transporte",
		name: "transporteId",
		type: "number",
		description: "ID del transporte asociado al comprobante de venta",
		default: 0,
		displayOptions: { show: { operation: ["listarFacturasVenta", "listarPedidosVenta"] } },
	},
	{
		displayName: "ID Pais",
		name: "idPais",
		type: "string",
		default: "",
		description: "ID del país por la cual se buscarán las provincias",
		displayOptions: { show: { operation: ["listarProvincias", "crearProveedor", "crearCliente"] } },
	},
	{
		displayName: "ID Provincia",
		name: "idProvincia",
		type: "string",
		default: "",
		description: "ID de la provincia por la cual se buscarán la información",
		displayOptions: { show: { operation: ["listarMunicipios", "crearProveedor", "crearCliente"] } },
	},
	{
		displayName: "ID Sucursal Física",
		name: "idSucursalFisica",
		type: "number",
		default: 0,
		description: "The ID of the physical branch to filter stock (optional)",
		displayOptions: {
			show: {
				operation: [
					"crearMovimientoStock",
					"crearMovimientoStock",
					"crearRemitoVenta",
					"crearRemitoCompra",
					"buscarProductoEnSucursal",
					"crearCompra",
					"crearOrdenCompra",
					"listarProductosPorSucursal",
					"listarFacturasVenta",
					"listarPedidosVenta",
				],
			},
		},
	},
	{
		displayName: "ID Valor Efectivo",
		name: "idValorEfectivo",
		type: "number",
		default: 0,
		displayOptions: { show: { esContado: [true] } },
	},
	{
		displayName: "ID De La Zona",
		name: "idZona",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearProveedor", "crearCliente"] } },
	},
	{
		displayName: "ID del descuento del proveedor",
		name: "idDescuentoProveedor",
		type: "number",
		default: 0,
		displayOptions: { show: { operation: ["crearProveedor"] } },
	},
	{
		displayName: "Importe",
		name: "importeValorEfectivo",
		type: "number",
		default: 0,
		displayOptions: { show: { esContado: [true] } },
	},
	{
		displayName: "Información De Envío",
		name: "envio",
		required: true,
		type: "json",
		default: {},
		description: "Shipping info from the order",
		displayOptions: { show: { operation: ["registrarCobro"] } },
	},
	{
		displayName: "Lista ID",
		name: "idList",
		type: "number",
		default: 0,
		description: "ID de la lista para buscar los precios de los articulos",
		displayOptions: {
			show: { operation: ["consultarPrecioProducto", "crearVenta", "estadisticaVentaRanking"] },
		},
	},
	{
		displayName: "Letra Del Documento De La Compra",
		name: "letraDocumento",
		type: "string",
		default: "",
		placeholder: "A",
		description: "Letra del documento de la compra de la factura",
		displayOptions: {
			show: {
				operation: ["crearCompra", "crearOrdenCompra", "crearRemitoCompra", "crearRemitoVenta"],
			},
		},
	},
	{
		displayName: "Migración Completa",
		name: "migracionCompleta",
		type: "boolean",
		default: false,
		description: "Whether to return only the first response without expanding group variants",
		displayOptions: { show: { operation: ["listarProductosDisponibles"] } },
	},
	{
		displayName: "Nombre Del Tipo De Comprobante",
		name: "nombreTipoComprobante",
		type: "string",
		default: "",
		placeholder: "Factura de compras",
		description: "Nombre del tipo de comprobante de la factura",
		displayOptions: { show: { operation: ["crearCompra"] } },
	},
	{
		displayName: "Nombre Del Articulo",
		name: "nombreArticulo",
		type: "string",
		default: "",
		placeholder: "Alfajores",
		displayOptions: { show: { operation: ["buscarProductos", "listarProductosPorSucursal"] } },
		description: "El nombre del producto a buscar",
	},
	{
		displayName: "Numero Del Documento De La Compra",
		name: "numeroFactura",
		type: "number",
		default: 0,
		placeholder: "1",
		description: "Numero del documento de la compra de la factura",
		displayOptions: {
			show: {
				operation: ["crearCompra", "crearOrdenCompra", "crearRemitoCompra", "crearRemitoVenta"],
			},
		},
	},
	{
		displayName: "Observaciones",
		name: "observacionesValorEfectivo",
		type: "string",
		default: "",
		displayOptions: { show: { esContado: [true] } },
	},
	{
		displayName: "Proveedor ID",
		name: "proveedorId",
		type: "number",
		required: true,
		default: 0,
		description: "ID del proveedor usado para buscar dentro del sistema",
		displayOptions: {
			show: {
				operation: ["crearOrdenCompra", "buscarProveedor", "listarOrdenesCompra", "crearRemitoCompra"],
			},
		},
	},
	{
		displayName: "Punto De Venta",
		name: "puntoDeVenta",
		type: "number",
		default: 0,
		placeholder: "1",
		description: "Numero del punto de venta del documento",
		displayOptions: {
			show: {
				operation: ["crearOrdenCompra", "crearVenta", "crearCompra", "crearRemitoCompra", "crearRemitoVenta"],
			},
		},
	},
	{
		displayName: "Razón Social",
		name: "razonSocial",
		type: "string",
		default: "",
		description: "Razón social del cliente para buscar",
		displayOptions: {
			show: {
				operation: ["buscarContribuyente", "buscarClientes", "crearProveedor", "crearPedidoVenta", "listarProveedores", "crearOrdenCompra", "crearCliente"],
			},
		},
	},
	{
		displayName: "Cantidad De Items",
		name: "cantidadDeItems",
		type: "number",
		default: 1,
		displayOptions: {
			show: { operation: ["estadisticaVentaRanking"] },
		},
	},
	{
		displayName: "Rubro ID",
		name: "rubroId",
		type: "string",
		default: "",
		description: "ID Rubros used to search the articles",
		displayOptions: {
			show: {
				operation: ["estadisticaVentaRanking", "listarProductosPorSucursal", "listarSubRubros"],
			},
		},
	},
	// {
	// 	displayName: "SKU",
	// 	name: "sku",
	// 	type: "string",
	// 	default: "",
	// 	required: true,
	// 	description: "The SKU (product code) to search for",
	// 	displayOptions: { show: { operation: ["buscarProductoPorCodigo"] } },
	// },
	{
		displayName: "Sub-Rubros IDs",
		name: "idsSubRubros",
		type: "string",
		default: "",
		description: "Client ID used to search the articles",
		displayOptions: { show: { operation: ["listarCategorias", "listarProductosPorSucursal"] } },
	},
	{
		displayName: "Sucursales Físicas - IDs Lista",
		name: "branchOfficeIds",
		type: "string",
		required: true,
		default: "7345",
		description: "Physical branch ID separated by comma",
		displayOptions: { show: { operation: ["consultarStock"] } },
	},
	{
		displayName: "Ultima Modificacion Imagenes",
		name: "lastModifiedImg",
		type: "json",
		required: true,
		default: {},
		displayOptions: { show: { operation: ["sincronizarImagenes"] } },
	},
	{
		displayName: "Usuario",
		name: "username",
		type: "string",
		default: "",
		displayOptions: {
			show: { operation: ["verificarCredencialesOperador", "listarOperadoresMoviles"] },
		},
	},
	{
		displayName: "Código",
		name: "codigo",
		type: "number",
		default: 0,
		displayOptions: {
			show: {
				operation: ["listarProveedores"],
			},
		},
	},
	{
		displayName: "Correo",
		name: "email",
		type: "string",
		placeholder: "name@email.com",
		default: "",
		displayOptions: {
			show: {
				operation: ["listarOperadoresMoviles"],
			},
		},
	},
	{
		displayName: "ID Marca Articulo",
		name: "IdMarcaArticulo",
		type: "string",
		placeholder: "3",
		default: "",
		displayOptions: {
			show: {
				operation: ["listarProductosPorSucursal"],
			},
		},
	},
	{
		displayName: "ID Categoria Articulo",
		name: "IdCategoriaArticulo",
		type: "string",
		placeholder: "3",
		default: "",
		displayOptions: {
			show: {
				operation: ["listarProductosPorSucursal"],
			},
		},
	},
	{
		displayName: "Simplified Output",
		name: "simplifiedOutput",
		type: "boolean",
		default: false,
		description: "Whether to return only the most useful top-level fields",
		displayOptions: {
			show: {
				operation: [
					"buscarProductos",
					"buscarProductoPorCodigo",
					"listarProductosDisponibles",
					"listarTodosLosProductos",
					"consultarPrecioProducto",
					"listarProductosPorSucursal",
					"buscarProductoEnSucursal",
					"buscarClientes",
					"buscarClientePorCuit",
					"listarClientes",
					"consultarSaldoCliente",
					"verDetalleSaldoCliente",
					"listarFacturasCobros",
					"listarFacturasVenta",
					"listarFacturasVentasPorID",
					"listarPromocionesComercialesCliente",
					"buscarContribuyente",
					"listarComprobantesVenta",
					"listarPedidosVenta",
					"listarPedidosVentaFiltrados",
					"estadisticaVentaRanking",
					"listarCobros",
					"listarCompras",
					"listarComprobantesCompra",
					"listarOrdenesCompra",
					"verDetalleOrdenCompra",
					"listarProveedores",
				],
			},
		},
	},
];

export const CentumFields: INodeProperties[] = [...getArticulo];

export const HttpOptions: INodeProperties[] = [
	{
		displayName: "Ajustes HTTP",
		name: "httpSettings",
		type: "collection",
		placeholder: "Configuración avanzada",
		default: {},
		options: [
			{
				displayName: "Paginación",
				name: "pagination",
				type: "options",
				options: [
					{
						name: "Paginación Personalizada",
						value: "custom",
						description: "Permite definir la cantidad de ítems por página",
					},
					{
						name: "All",
						value: "all",
						description: "Trae todos los ítems paginando internamente sin opción de modificar cantidad por página ni intervalo",
					},
				],
				default: "custom",
				description: "Controla cómo se solicita la información paginada",
			},
			{
				displayName: "Ítems Por Página",
				name: "cantidadItemsPorPagina",
				type: "number",
				default: 100,
				typeOptions: {
					minValue: 1,
				},
				displayOptions: {
					show: {
						pagination: ["custom"],
					},
				},
				description: "Cantidad de ítems a solicitar por página (solo para modo personalizado)",
			},
			{
				displayName: "Intervalo Por Pagina(ms)",
				name: "intervaloPagina",
				type: "number",
				default: 1000,
				typeOptions: {
					minValue: 500,
				},
				displayOptions: {
					show: {
						pagination: ["custom"],
					},
				},
				description: "Intervalo de tiempo entre cada solicitud (En milisegundos)",
			},
			{
				displayName: "Número De Página Inicial",
				name: "numeroPagina",
				type: "number",
				default: 1,
				typeOptions: {
					minValue: 1,
				},
				displayOptions: {
					show: {
						pagination: ["custom"],
					},
				},
				description: "Número de página desde donde comenzar la paginación (por defecto comienza desde la página 1)",
			},
		],
		displayOptions: {
			show: {
				operation: ["listarClientes", "listarTodosLosProductos", "listarProductosDisponibles"],
			},
		},
	},
	{
		displayName: "Debug Options",
		name: "debugSettings",
		type: "collection",
		placeholder: "Advanced Options",
		default: {},
		options: [
			{
				displayName: "Enable Debug Logging",
				name: "enableDebugLogging",
				type: "boolean",
				default: false,
				description: "Whether to log sanitized request metadata for debugging",
			},
			{
				displayName: "Endpoint Filter",
				name: "debugEndpointContains",
				type: "string",
				default: "",
				placeholder: "/Ventas/FiltrosVentaConsulta",
				description: "Only log requests whose URL contains this value",
				displayOptions: {
					show: {
						enableDebugLogging: [true],
					},
				},
			},
		],
	},
];
